### ISSUE TITLE
Updating Cash/Voucher Activities in WASH Cluster

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#1]
To enable the cash amount inputs for Cash/Voucher Activities

- [x] Enable the disabled/non-disabled category
- [x] Enable other cash amount inputs needed as in MPC
- [x] Enable all possible options for transfer type (HH and Individual)
- [x] Enable only the right grant type (currently it is enabling all possible options)

**Comment by fakhrihawari** [comment]
Note: activities.csv

Row 310,311,417,418
