### ISSUE TITLE
Validate before successfully copy previous month

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#101]
Just realized that the system hasn't checked the beneficiary field if it's available in the current month or not.

If it's not, then please give the warning message the same as in while checking activity.

check if there're any other field that need to be checked.

**Comment by fakhrihawari** [comment]
<img width="1161" alt="Screen Shot 2021-09-08 at 14 32 49" src="https://user-images.githubusercontent.com/12655589/132466132-d67baf07-6714-4cfb-8cf6-d38d6b5b028d.png">

**Comment by rafinkanisa** [comment]
Please change "The Beneficiary type has ended ...." to "The Beneficiary type is not available in the current month ....."

How is the behaviour of the system when a user add an activity in monthly progress then click copy previous month button?
Would the added activity be overwritten with the copied one or is it added in different row?

Because, if you check the videos, the activity is not overwritten

and if user click submit, would it scrolled up to the incorrect row at the top or to the last one?
I think it should scrolled to the first incorrect row.

**Comment by fakhrihawari** [comment]
PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/250
