### ISSUE TITLE
RH SO two cluster with same name

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#102]
I've spot in Somalia, the system has 2 cluster with the same name in the filter.
May you please check?
<img width="282" alt="Screen Shot 2021-09-08 at 10 45 09" src="https://user-images.githubusercontent.com/28089698/132443151-0611e9bc-c62c-4b8b-97e2-4e04a0fc3d35.png">

I think this is related to cleaning up the data.

**Comment by fakhrihawari** [comment]
No, it's not related to cleaning up data, cause i never change cluster_id

But I already found the user with a bug i will fix it now
