### ISSUE TITLE
Search Bar in Target Beneficiaries Disordered

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#107]
Please fix below

<img width="1329" alt="Screen Shot 2021-09-15 at 13 20 01" src="https://user-images.githubusercontent.com/28089698/133381323-d902cf89-5327-4db4-a2a9-8d504e2bb74f.png">

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/drfaustusfade/ngm-reportHub/pull/251
