### ISSUE TITLE
Table unresponsive in lower resolution

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#108]
Please make this responsive.

![image](https://user-images.githubusercontent.com/28089698/133394178-d4eac64c-82ca-430d-bd9a-e7f654f3eb5b.png)

![image](https://user-images.githubusercontent.com/28089698/133393883-7dcb00c8-825a-458f-bc83-69db0d92e641.png)

would be great if in the long term, the user should be able to choose the column they would like to see.

please try in 1366 x 768 as it is the common resolution for users to use or you could also try 1024

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/drfaustusfade/ngm-reportHub/pull/244/files
