### ISSUE TITLE
Fixing Bugs on Update Warehouse Province & District

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#109]
When checking the Warehouse, I could see there are some warehouses that province dropdown is blank like below

![reporthub org_desk_ (1)](https://user-images.githubusercontent.com/28089698/133591116-5cfb679d-a2e1-492f-bf92-4caf090641f4.png)

This was caused by the warehouse is still using the old province & district administrative boundaries.

Please fix below bugs :

- [x] Error edit warehouse location
- [x] When I changed to the new one, only the code that was updated but not with the warehouse_lng and warehouse_lat

**Comment by fakhrihawari** [comment]
PR 
https://github.com/drfaustusfade/ngm-reportHub/pull/249
