### ISSUE TITLE
Dashboard Filter

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#11]
As we're doing a monthly report to the Country Director, we'll have to include the screenshots of Timestamp stats, Timestamp map, etc. Previously, it was done manually by editing the code from reporting_period to createdAt. Create a filter that can be easily used in the interface. This filter should only be visible to limited users such as admin. Applied this filter on 5W Dashboard.

**Comment by fakhrihawari** [comment]
Branch: 
https://github.com/fakhrihawari/ngm-reportHub/tree/add-filter-timestamp-hrp
https://github.com/fakhrihawari/ngm-reportEngine/tree/update-filter5wactivity

**Comment by rafinkanisa** [comment]
Could you share some screenshots?
Which user role will be able to see this filter?

**Comment by fakhrihawari** [comment]
<img width="1680" alt="Screen Shot 2021-06-23 at 15 56 10" src="https://user-images.githubusercontent.com/12655589/123067878-956c6500-d43b-11eb-805e-86c34c0e7018.png">

For now just superadmin

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/177
https://github.com/drfaustusfade/ngm-reportEngine/pull/37/files

Updated on DEV and PROD
