### ISSUE TITLE
Avoid Multiple Warehouse Name in the same Location

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#110]
Currently, it's possible to add the same warehouse name with the same province & district.
ESNFI cluster was the one who's requesting to make the system couldn't add the same warehouse name in the same exact location.

Please apply a validation rule when users are adding a new warehouse or edit the existing warehouse.

**Comment by fakhrihawari** [comment]
Link PR : https://github.com/drfaustusfade/ngm-reportHub/pull/249
