### ISSUE TITLE
Make input SADD as mandatory for ESNFI if HH is added

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#111]
ESNFI cluster is requesting to make the system capable of identifying when partners are inputting HH numbers, they should also input the disaggregated data

This is because it is often found in the submitted reports partners were specifying the HH but the SADD is still 0

Please make the system validate the data when submit button is clicked. Apply the following rule :
If HH > 0 the total SADD should be > 0
so, each of the input columns of boys, girl, men, women, eld_men, eld_women could still have 0 inputs but the totals shouldn't be 0 if HH isn't 0

This rule should only be applied to ESNFI activities only. Other clusters haven't asked about it so just let it be.

Apply this fix before the winterization period

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/252
