### ISSUE TITLE
Sort Warehouse by the most recent one

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#113]
Minor Update on Stock Report Interface

Currently, the recent added warehouse name would automatically be put at the most bottom of the list

From UI/UX perspective, it would be better to sort the list from top to down by the most recent one first
Update only on below page :
<img width="1256" alt="Screen Shot 2021-09-16 at 14 38 58" src="https://user-images.githubusercontent.com/28089698/133822702-350a59c6-3e5e-4004-a1d2-008b43badcb1.png">

Please update this before the upcoming training for ESNFI

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/252
