### ISSUE TITLE
Minor Update on Interface

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#114]
Minor updates on interface as below picture :
<img width="1240" alt="Screen Shot 2021-09-16 at 14 16 58" src="https://user-images.githubusercontent.com/28089698/133823002-834ce9a8-3b90-4d0e-9d29-7db8544b29b5.png">

Not only just the Stock Report page, please also applied the updated interface in Monthly Progress

Please also fix the jumbled button in lower resolution (I used 1366)
![stock report button jumbled](https://user-images.githubusercontent.com/28089698/133824064-0981e56f-a537-41a1-9a33-1b8d0f057c81.png)

**Tasks**

- [x] Update Monthly Stock Report page
- [x] Update Monthly Progress

Please update before the upcoming training for ESNFI

**Comment by fakhrihawari** [comment]
Link PR : https://github.com/drfaustusfade/ngm-reportHub/pull/252
