### ISSUE TITLE
Activity Response Filter in 5W Filter

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#115]
I'm thinking to add activity response in the filter also
So, it's possible to show the winterization activity by filter

This is an anticipation action because previously ESNFI is requesting to have an entirely new dashboard for Winterization

**Comment by rafinkanisa** [comment]
Adding the project detail also in 5W

When I filter by the activity response, the project detail automatically select the winterization filter also
<img width="301" alt="Screen Shot 2021-10-22 at 10 40 21" src="https://user-images.githubusercontent.com/28089698/138390148-45e5c06b-333c-4f23-b310-8f85a699f2da.png">

link : https://dev.reporthub.org/desk/#/cluster/5w/emro/af/all/all/all/all/all/all/all/2021-01-01/2021-10-22/true/all/winterization

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/44
