### ISSUE TITLE
RH ET Bugs on inputting stock report

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#116]
I found a bug in Stock Report in ET where Stock Type is mandatory but the list is not shown. I check it in Health cluster.
Also, the donor dropdown remains select ( - ) even though I have changed it to another donor.

https://user-images.githubusercontent.com/28089698/134618168-ef7e1590-99fb-4970-827a-33fcc20f0d54.mov

Is this on purpose?

Please kindly fix this issue

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/iMMAP/ngm-reportHub/pull/7/files
