### ISSUE TITLE
User Role after Register

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#12]
Currently, if registered as iMMAP, it will automatically give the new user a country admin role. It would be good if we don't automatically set every new user under iMMAP this role. Therefore, we can avoid any random attempt.

**Comment by fakhrihawari** [comment]
Branch:
https://github.com/fakhrihawari/ngm-reportHub/tree/update-default-role-for-immap

**Comment by fakhrihawari** [comment]
- [x] testing in local machin
- [x] tesing on DEV
- [x] test on PROD

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/157
