### ISSUE TITLE
RH ET Bugs on Download Monthly Activity in Monthly Report Page

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#122]
Kindly check the bugs on below link. I couldn't download the monthly activity report there

https://dev.reporthub.org/desk/#/cluster/projects/report/5ce282286de3c5925ead2730/5e5b17233aa441270ea8d74b

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/iMMAP/ngm-reportEngine/pull/2
