### ISSUE TITLE
RH ET Bugs on Monthly Report Date not showing

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#123]
Compared to the PROD :
https://reporthub.org/desk/#/cluster/projects/report/5ce282286de3c5925ead2730/5e5b17233aa441270ea8d74b

While in DEV :
https://dev.reporthub.org/desk/#/cluster/projects/report/5ce282286de3c5925ead2730/5e5b17233aa441270ea8d74b

Below date is not shown in DEV. Previously, it's showing but after some fixes, it's gone missing
<img width="1116" alt="Screen Shot 2021-09-30 at 16 09 56" src="https://user-images.githubusercontent.com/28089698/135424515-53125bed-cb46-45b3-8b35-8c1079513006.png">

Kindly fix the bugs

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/iMMAP/ngm-reportHub/pull/9
