### ISSUE TITLE
RH AF Bugs on Monthly Progress can't delete activities

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#124]
The SAF user is not able to delete their July activity report that has been inputted previously

I have also tried to delete the activity using my own account but strangely, the activities can't be deleted.

![image](https://user-images.githubusercontent.com/28089698/135426318-19048093-2d9a-4306-9657-035e3b4d6613.png)

<img width="559" alt="Screen Shot 2021-09-27 at 18 42 28" src="https://user-images.githubusercontent.com/28089698/135426415-3c856ebc-a90d-4ab7-87d5-94804503675f.png">

**Comment by fakhrihawari** [comment]
It is already fixed no need to update the code because the server is space is full.
