### ISSUE TITLE
Biweekly option in Project Plan

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#125]
Continuing from https://github.com/rafinkanisa/ngm-reportDesk/issues/112

Adding the option to report biweekly in the project plan

**Comment by rafinkanisa** [comment]
<img width="923" alt="Screen Shot 2021-10-01 at 09 44 56" src="https://user-images.githubusercontent.com/28089698/135558185-8d43ecb0-981d-4227-885d-383ffb8f8d70.png">

Change the text warning:

Would you like to do the reporting every 2 weeks (Biweekly)? Leave this **unchecked** if you would like to do the reporting on **Monthly basis**.

WARNING! Once you set to report on a biweekly basis you cannot change to a monthly basis. You can only set this once.

**Comment by rafinkanisa** [comment]
The ESNFI cluster leads mentioned that the biweekly option is only for the winterization project

I think, we would have to give the warning message for the user to inform that in ESNFI, for winterization they're demanding to report on biweekly basis.

Also, I thought that the Checkbox of Reporting Period is on Activity Plan section.

**Comment by rafinkanisa** [comment]
Could you also change to Report Period?

<img width="1241" alt="Screen Shot 2021-10-06 at 15 39 15" src="https://user-images.githubusercontent.com/28089698/136169709-28d33489-a74e-4092-9a5a-f155d88afd84.png">

and also change :
Reporting Period for this Activity Plan has already been set to Biweekly (twice a month)

**Comment by rafinkanisa** [comment]
I've tried the following action :
Tick Winterization for the whole project then Tick Biweekly and the state is not saved yet
Then I tried to untick the winterization checkbox (The Report Period section is hidden which is good) But, the biweekly checkbox is still in state ticked
Because when I save the Activity plan, it's saved as Biweekly

Kindly check at below
https://dev.reporthub.org/desk/#/cluster/projects/summary/615d6699fbb9454a20b5ce1d

Currently, the biweekly option should only be available for the ESNFI winterization project only

**Comment by rafinkanisa** [comment]
ASKING :
Is the biweekly option be available if user from another cluster creating activity plan using ESNFI cluster only?

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/52
https://github.com/iMMAP/ngm-reportEngine/pull/21
