### ISSUE TITLE
Blank Stock Purpose in Stock Report

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#129]
Kindly fix the issue in below screenshot

<img width="1104" alt="Screen Shot 2021-10-05 at 15 52 33" src="https://user-images.githubusercontent.com/28089698/135992085-c9c4566a-080e-4cb6-8389-1c7199c407c1.png">

**Comment by rafinkanisa** [comment]
Turns out that the Stock Purpose is blank because it has incoherent stock_item_purpose_id with stock_item_purpose_name 
This bug occurred because the "Copy Last Month" button has an incorrect function in the code.

TODO :

- [x] Fix the code
- [x] Identify all of the data which is incorrect
- [x] Perform query update to the correct one

@sud0su / @dodiws please share the query here

**Comment by fakhrihawari** [comment]
LInk PR: https://github.com/iMMAP/ngm-reportHub/pull/14/files 
for fix code
db.stock.aggregate([{
    $project: {
        _id: "$_id",
        stock_item_type: "$stock_item_type",
        stock_item_name: "$stock_item_name",
        stock_item_purpose_id: "$stock_item_purpose_id",
        stock_item_purpose_name: "$stock_item_purpose_name",
        report_year: "$report_year",
        admin0name: "$admin0name",
        compare: {
            $cond: {
                if: {
                    $and: [{
                        $eq: ["$stock_item_purpose_id", "prepositioned"]
                    }, {
                        $eq: ["$stock_item_purpose_name", "Prepositioned"]
                    }]
                },
                then: "preposioned True",
                else: {
                    $cond: {
                        if: {
                            $and: [{
                                $eq: ["$stock_item_purpose_id", "operational"]
                            }, {
                                $eq: ["$stock_item_purpose_name", "Operational"]
                            }]
                        },
                        then: "operational True",
                        else: "Not a preposioned and a operational"
                    }
                }
            },
        },
    }
}, {
    $match: {
        compare: "Not a preposioned and a operational",
        stock_item_purpose_id_isnull: {
            $eq: null
        },
        stock_item_purpose_name_isnull: {
            $eq: null
        },
    }
}, {
        $group: {
            _id: {
                report_year: "$report_year",
                admin0name: "$admin0name",
            },
            total: {
                $sum: 1
            }
        }
    }])
Query to perform correct one
db.stock.find({ admin0pcode: "AF", stock_item_purpose_name: 'Prepositioned', stock_item_purpose_id: { $ne: 'prepositioned' } }).count()
db.stock.find({ admin0pcode: "AF", stock_item_purpose_name: 'Prepositioned', stock_item_purpose_id: { $ne: 'prepositioned' } }).forEach(function (x) {
    print(x.stock_item_purpose_id, x.stock_item_purpose_name)
})
db.stock.find({ admin0pcode: "AF", stock_item_purpose_name: 'Prepositioned', stock_item_purpose_id: { $ne: 'prepositioned' } }).forEach(function (x) {
    if (x.stock_item_purpose_id !== 'prepositioned') {
        x.stock_item_purpose_id = 'prepositioned';
        db.stock.save(x)
    };
})
db.stock.find({ admin0pcode:"AF",stock_item_purpose_name: 'Prepositioned' }).forEach(function (x) {
    if (x.stock_item_purpose_id !== 'prepositioned') {
        x.stock_item_purpose_id = 'prepositioned';
        db.stock.save(x)
    };
})
db.stock.find({ admin0pcode: "AF", stock_item_purpose_name: 'Operational', stock_item_purpose_id: { $ne: 'operational' } }).count()
db.stock.find({ admin0pcode: "AF", stock_item_purpose_name: 'Operational', stock_item_purpose_id: { $ne: 'operational' } }).forEach(function (x) {
    print(x.stock_item_purpose_id, x.stock_item_purpose_name)
})
db.stock.find({ admin0pcode: "AF", stock_item_purpose_name: 'Operational', stock_item_purpose_id: { $ne: 'operational' } }).forEach(function (x) {
    if (x.stock_item_purpose_id !== 'operational') {
        x.stock_item_purpose_id = 'operational';
        db.stock.save(x)

    };
})
db.stock.find({ admin0pcode:"AF",stock_item_purpose_name: 'Operational' }).forEach(function (x) {
    if (x.stock_item_purpose_id !== 'operational') {
        x.stock_item_purpose_id = 'operational';
        db.stock.save(x)

    };
})
