### ISSUE TITLE
Bugs on Activity Plan

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#13]
For some reason, there's an activity plan in the WASH Cluster that doesn't save the changes that have been made. See the video for more details.

https://user-images.githubusercontent.com/28089698/117075649-64d34d80-ad5f-11eb-951e-0a6fbe1f500e.mov

**Comment by fakhrihawari** [comment]
Link PR: 
https://github.com/drfaustusfade/ngm-reportHub/pull/138/files

Updated on DEV and PROD
