### ISSUE TITLE
Duplicate Stock Report

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#130]
It is identified that the "Copy Last Month" button can be clicked more than once. Related to https://github.com/rafinkanisa/ngm-reportDesk/issues/128
This is resulting to duplicate submitted data in the stock report.

Please identify all of the duplicated data from all organizations.
Duplicated data has the same data submitted in all row

Kindly share your query here

**Comment by fakhrihawari** [comment]
queries.push({
    'key': 'total_duplicates_group_by_org_year_month',
    'desc': 'Total duplicates group by org, year, month',
    'query': () => { 
        return db.stock.aggregate(
            [{
                $match: {
                    report_year: 2021,
                    admin0pcode: "AF",
                    // organization_tag: "akah",
                }
            }, {
                $sort: {
                    "_id": 1,
                }
            }, {
                $group: {
                    _id: {
                        report_id: "$report_id",
                        organization_tag: "$organization_tag",
                        location_id: "$location_id",
                        cluster_id: "$cluster_id",
                        stock_item_type: "$stock_item_type",
                        stock_targeted_groups_id: "$stock_targeted_groups_id",
                        stock_status_name: "$stock_status_name",
                        unit_type_id: "$unit_type_id",
                        number_in_stock: "$number_in_stock",
                        beneficiaries_covered: "$beneficiaries_covered",
                        admin0pcode: "$admin0pcode",
                        report_status: "$report_status",
                        reporting_period: "$reporting_period",
                        number_in_pipeline: "$number_in_pipeline",
                        report_year: "$report_year",
                        report_month: "$report_month",
                    },
                    _ids: {
                        $addToSet: "$_id"
                    },
                    first_id: { $first: "$_id" },
                    last_id: { $last: "$_id" },
                    count: {
                        $sum: 1
                    }
                }
            }, {
                $match: {
                    count: {
                        $gte: 2
                    }
                }
            }]
        )
    }
})

queries.push({
    'key': 'total_unique_and_duplicate_reports',
    'desc': 'Total unique and duplicate reports\n:\ntotal_reports = total_unique + total_not_unique\nduplicates = total_reports - total_with_duplicates_removed\ntotal_not_unique_with_duplicates_removed = total_not_unique - duplicates\ntotal_with_duplicates_removed = total_unique + total_not_unique_with_duplicates_removed',
    'query': () => { 
        return db.stock.aggregate(
            [{
                $match: {
                    report_year: 2021,
                    admin0pcode: "AF"
                }
            }, {
                // sort _id before apply $first or $last $_id
                $sort: {
                    "_id": 1,
                }
            }, {
                $group: {
                    _id: {
                        report_id: "$report_id",
                        organization_tag: "$organization_tag",
                        location_id: "$location_id",
                        cluster_id: "$cluster_id",
                        stock_item_type: "$stock_item_type",
                        stock_targeted_groups_id: "$stock_targeted_groups_id",
                        stock_status_name: "$stock_status_name",
                        unit_type_id: "$unit_type_id",
                        number_in_stock: "$number_in_stock",
                        beneficiaries_covered: "$beneficiaries_covered",
                        admin0pcode: "$admin0pcode",
                        report_status: "$report_status",
                        reporting_period: "$reporting_period",
                        number_in_pipeline: "$number_in_pipeline",
                        report_year: "$report_year",
                        report_month: "$report_month",
                    },
                    _ids: {
                        $addToSet: "$_id"
                    },
                    first_id: { $first: "$_id" },
                    last_id: { $last: "$_id" },
                    count: {
                        $sum: 1
                    }
                }
            }, {
                $group: {
                    _id: null,
                    total_reports: {
                        $sum: "$count"
                    },
                    total_unique: {
                        "$sum": {
                            "$cond": [
                                { "$eq": ["$count", 1] },
                                "$count",
                                0
                            ]
                        }
                    },
                    total_not_unique: {
                        "$sum": {
                            "$cond": [
                                { "$gte": ["$count", 2] },
                                "$count",
                                0
                            ]
                        }
                    },
                    total_not_unique_with_duplicates_removed: {
                        "$sum": {
                            "$cond": [
                                { "$gte": ["$count", 2] },
                                1,
                                0
                            ]
                        }
                    },
                    total_with_duplicates_removed: {
                        $sum: 1
                    },
                }
            }, {
                $project: {
                    _id: false,
                    total_reports: true,
                    total_unique: true,
                    total_not_unique: true,
                    total_not_unique_with_duplicates_removed: true,
                    duplicates: { $subtract: ["$total_reports", "$total_with_duplicates_removed"], },
                    total_with_duplicates_removed: true, // = total_unique + total_not_unique - duplicates
                }
            }]
        )
    }
})

queries.push({
    'key': 'all_organization_reports',
    'desc': 'All organization reports ',
    'query': () => { 
        return db.stock.aggregate(
            [{
                $match: {
                    report_year: 2021,
                    admin0pcode: "AF"
                }
            }, {
                $group: {
                    _id: {
                        organization_tag: "$organization_tag",
                    },
                }
            }, {
                $group: {
                    _id: null,
                    organizations: {
                        $addToSet: "$_id.organization_tag"
                    },
                    total: {
                        $sum: 1
                    },
                }
            }]
        )
    }
})

queries.push({
    'key': 'organization_with_duplicate_reports',
    'desc': 'Organization with duplicate reports ',
    'query': () => { 
        return db.stock.aggregate(
            [{
                $match: {
                    report_year: 2021,
                    admin0pcode: "AF"
                }
            }, {
                // sort _id before apply $first or $last $_id
                $sort: {
                    "_id": 1,
                }
            }, {
                $group: {
                    _id: {
                        report_id: "$report_id",
                        organization_tag: "$organization_tag",
                        location_id: "$location_id",
                        cluster_id: "$cluster_id",
                        stock_item_type: "$stock_item_type",
                        stock_targeted_groups_id: "$stock_targeted_groups_id",
                        stock_status_name: "$stock_status_name",
                        unit_type_id: "$unit_type_id",
                        number_in_stock: "$number_in_stock",
                        beneficiaries_covered: "$beneficiaries_covered",
                        admin0pcode: "$admin0pcode",
                        report_status: "$report_status",
                        reporting_period: "$reporting_period",
                        number_in_pipeline: "$number_in_pipeline",
                        report_year: "$report_year",
                        report_month: "$report_month",
                    },
                    _ids: {
                        $addToSet: "$_id"
                    },
                    first_id: { $first: "$_id" },
                    last_id: { $last: "$_id" },
                    count: {
                        $sum: 1
                    }
                }
            }, {
                $match: {
                    count: {
                        $gte: 2
                    }
                }
            }, {
                $group: {
                    _id: {
                        organization_tag: "$_id.organization_tag"
                    },
                    total_not_unique: {
                        $sum: "$count"
                    },
                    total_not_unique_with_duplicates_removed: {
                        $sum: 1
                    }
                }
            }, {
                $project: {
                    _id: true,
                    total_not_unique: true,
                    total_not_unique_with_duplicates_removed: true,
                    duplicates: { $subtract: ["$total_not_unique", "$total_not_unique_with_duplicates_removed"], },
                }
                // }, {
                //     $group: {
                //         _id: null,
                //         organizations: {
                //             $addToSet: "$_id.organization_tag"
                //         },
                //         total: {
                //             $sum: 1
                //         },
                //     }
            }]
        )
    }
})

**Comment by fakhrihawari** [comment]
Already removed the duplicated stock on PROD
