### ISSUE TITLE
Browser is freezing after using Copy Last Month button

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#132]
Some of the partners are reporting that their browser is freeze up after using the copy last month button.

The link to their reports :
https://reporthub.org/desk/#/cluster/projects/report/60adeb1acbb7708b21a04683/612edea27fd758f36030d28c

https://reporthub.org/desk/#/cluster/projects/report/5faa586b399d8e9d34eeff5a/612edea27fd758f36030d1ff

Those 2 reports are copying 136 rows and more than 200 rows respectively. I think, the validation making the website takes too much operation handled in 1 time

Kindly enhance the performance of the website

**Comment by fakhrihawari** [comment]
Link PR: iMMAP/ngm-reportHub#36
