### ISSUE TITLE
RH NG issues with copy button

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#134]
I'm not sure if the copy button right now has some bugs due to some changes we did previously

kindly check how could this report has a big number of data submitted (11 Million)
![image](https://user-images.githubusercontent.com/28089698/136576021-5d73dcfb-57d6-4b43-af28-4794d9429fea.png)

Link :
https://reporthub.org/desk/#/cluster/projects/report/603f5a0810f17c1e3523e2ef/612edea27fd758f36030d213

but after some time, strangely, it's changed to around 3 Million
<img width="1680" alt="Screen Shot 2021-10-08 at 20 02 03" src="https://user-images.githubusercontent.com/28089698/136575767-61b4b76b-0dcf-4e98-9b83-7f49929d4ada.png">

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/iMMAP/ngm-reportHub/pull/36
