### ISSUE TITLE
RH NG detail activity not show up

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#135]
The detail activity in this project is not show up as below screenshot

<img width="1680" alt="Screen Shot 2021-10-08 at 21 06 07" src="https://user-images.githubusercontent.com/28089698/136576372-df3c6829-22c0-4ae3-8a67-c2578528b58c.png">

Link Feb 2021 Report : https://reporthub.org/desk/#/cluster/projects/report/603f5a0810f17c1e3523e2ef/603f5a0810f17c1e3523e308

This project could only show the details activity on Feb 2021 but from March-August it's missing.
I suspect that this user has been using the copy button and the copy functionality has a missing id to the activity details. Not sure if it's true. Kindly check

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/27
https://github.com/iMMAP/ngm-reportHub/pull/28
