### ISSUE TITLE
Biweekly in 5W Dashboard

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#136]
When I click the biweekly period in the filter, I could still download the stock report but, stock report is only in monthly basis

I think this will make confusion if this keeps going on.

I think we could hide it

**Comment by rafinkanisa** [comment]
Good to go!

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/52
https://github.com/iMMAP/ngm-reportEngine/pull/21
