### ISSUE TITLE
Biweekly in 5W Dashboard duplicate reporting period filter

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#137]
Is it just my laptop or do you also seeing the same thing?
I use the tester account with cluster role
When I go to the 5W Dashboard, it shows duplicate filter as shown below picture

<img width="1680" alt="Screen Shot 2021-10-12 at 20 20 52" src="https://user-images.githubusercontent.com/28089698/136964392-9680d8c7-7ad1-435f-a066-8c0e129f4ca8.png">

This is the link : https://dev.reporthub.org/desk/#/cluster/5w/emro/af/all/all/esnfi/all/all/all/all/2021-01-01/2021-10-12/true/all

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/52
https://github.com/iMMAP/ngm-reportEngine/pull/21
