### ISSUE TITLE
Biweekly in Progress Admin Data Download

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#139]
I could still see some project which not biweekly is able to be seen on the downloaded data at the progress admin
I'm using tester user with Organization admin

Kindly also filter based on biweekly/monthly/all on :

- [x] Project Summaries
- [x] Target Locations

Link : https://dev.reporthub.org/desk/#/cluster/admin/emro/af/esnfi/all/unhcr/activity/2021-08-01/2021-10-31/bi-weekly/all

make this identifiable in the name of the file for all downloaded data :
- [x] Project Summaries
- [x] Target Locations
- [x] Activity Reports To Do
- [x] Activity Reports Complete
- [x] Beneficiaries

you can put biweekly in the middle of the file name

**Comment by rafinkanisa** [comment]
I've checked.

Target location is ok, but for the others it's not
The file name is ok too

**Comment by rafinkanisa** [comment]
I've tried to download the beneficiaries.csv using the tester account as common user with the following link
https://dev.reporthub.org/desk/#/cluster/admin/emro/af/esnfi/all/unhcr/activity/2021-09-01/2021-09-30/all/all

but, I couldn't find the submitted report on the 2nd period of biweekly. Could you please check?

**Comment by rafinkanisa** [comment]
I couldn't download project summaries from my admin if ALL reporting period is selected
https://dev.reporthub.org/desk/#/cluster/admin/emro/af/esnfi/all/unhcr/activity/2021-09-01/2021-09-30/all/all

kindly fix

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/52
https://github.com/iMMAP/ngm-reportEngine/pull/21
