### ISSUE TITLE
Bugs on WASH CVA

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#14]
For some reason, the CVA options can't be clicked. Follow the step below to produce the bugs:

1. Click Assistance through Voucher Distribution
2. Change to Assistance through Cash Distribution
3. Select Details

Then you'll get options available in Details can't be clicked. Identify the reason and apply the fix. See the details on video below.

https://user-images.githubusercontent.com/28089698/117078039-57b85d80-ad63-11eb-96ed-a76a97a89d46.mov

**Comment by fakhrihawari** [comment]
Link PR : https://github.com/drfaustusfade/ngm-reportHub/pull/134
Updated on PROD and DEV
