### ISSUE TITLE
Biweekly download Target Locations in Progress Admin Page Error

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#140]
I couldn't download the target location in progress admin after filter by biweekly in the progress admin page

Kindly fix this issue

<img width="1680" alt="Screen Shot 2021-10-13 at 12 41 26" src="https://user-images.githubusercontent.com/28089698/137075009-144e0ff5-8fe1-4cda-892a-fe6bfb8bba18.png">

shows error 500 in the console for the API

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/52
https://github.com/iMMAP/ngm-reportEngine/pull/21
