### ISSUE TITLE
Biweekly in the Biweekly Progress some words still Monthly

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#143]
Change the Monthly to Biweekly

<img width="443" alt="Screen Shot 2021-10-14 at 16 38 34" src="https://user-images.githubusercontent.com/28089698/137292519-460d48c3-86da-4702-8e2c-fbdac10ac45c.png">

<img width="335" alt="Screen Shot 2021-10-14 at 16 43 40" src="https://user-images.githubusercontent.com/28089698/137293255-fb7c4b89-8040-4afa-b967-baae9c2fc55f.png">

Link : https://dev.reporthub.org/desk/#/cluster/projects/report/615ec585fbb9454a20b5ce41/615ec585fbb9454a20b5ce48

If it's not possible, then just remove the "Monthly"

**Comment by rafinkanisa** [comment]
<img width="927" alt="Screen Shot 2021-10-28 at 16 09 37" src="https://user-images.githubusercontent.com/28089698/139225245-4a77d46e-bfef-41cc-b468-694ce6c9f793.png">

Please also change in here to biweekly

**Comment by fakhrihawari** [comment]
<img width="546" alt="Screen Shot 2021-10-28 at 16 07 38" src="https://user-images.githubusercontent.com/12655589/139229947-59dc4b27-525d-4c9c-8dcb-eb210636ae4f.png">

<img width="1152" alt="Screen Shot 2021-10-28 at 16 19 05" src="https://user-images.githubusercontent.com/12655589/139229985-a8d96a03-70fe-4827-99e3-6c46b126bd24.png">

<img width="265" alt="Screen Shot 2021-10-28 at 16 40 15" src="https://user-images.githubusercontent.com/12655589/139230575-db289a35-49aa-4d32-8b11-efff3d0dbe63.png">

**Comment by rafinkanisa** [comment]
OK

**Comment by fakhrihawari** [comment]
Updated on DEV

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/52
