### ISSUE TITLE
RH AF Health Updates Activity Name

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#145]
As requested by the Health cluster

Kindly update the following activity into a new name
Risk Community and Community Engagement
to :
Risk Communication and Community Engagement

Required todo :
Update the database

**Comment by fakhrihawari** [comment]
Script:
db.beneficiaries.find({activity_description_id:"risk_community_engagement",activity_description_name:"Risk Community and Community Engagement"}).count()
db.targetbeneficiaries.find({activity_description_id:"risk_community_engagement",activity_description_name:"Risk Community and Community Engagement"}).count()
db.budgetprogress.find({activity_description_id:"risk_community_engagement",activity_description_name:"Risk Community and Community Engagement"}).count()

db.beneficiaries.update({activity_description_id:"risk_community_engagement",activity_description_name:"Risk Community and Community Engagement"},{$set:{activity_description_name:"Risk Communication and Community Engagement"}},{multi:true})

db.targetbeneficiaries.update({activity_description_id:"risk_community_engagement",activity_description_name:"Risk Community and Community Engagement"},{$set:{activity_description_name:"Risk Communication and Community Engagement"}},{multi:true})

db.budgetprogress.update({activity_description_id:"risk_community_engagement",activity_description_name:"Risk Community and Community Engagement"},{$set:{activity_description_name:"Risk Communication and Community Engagement"}},{multi:true})

**Comment by fakhrihawari** [comment]
Updated on DEV and PROD
