### ISSUE TITLE
RH AF Download Target Beneficiaries

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#146]
This is an anticipation action for ESNFI cluster.

Currently, in ReportHub, we don't have the functionality to download all of the activity plan (the target beneficiaries)
Please enable this functionality in the "My Admin" page

What column should be downloaded more or less is the same as with the beneficiary.csv

**Comment by rafinkanisa** [comment]
Hide column delivery_type_name in the download file

**Comment by fakhrihawari** [comment]
Ok, already on branch

**Comment by fakhrihawari** [comment]
Link PR Request: https://github.com/iMMAP/ngm-reportHub/pull/54/files
