### ISSUE TITLE
RH AF Winterization filter in the My Admin Page

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#147]
Put the same "winterization" filter in the My Admin page

Keep in mind that there are 2 ways to define "winterization" by project / by activities
So you should enable 2 filters in the My Admin page

- [x] Project Response
- [x] Activity Response

Once this filter is clicked, the available download data should automatically filter only the winterization response
Need to check that the filter works on below:

- [x] Download Beneficiaries Data
- [x] Download Activity Reports Complete
- [x] Download Activity Reports To Do
- [x] Download Project Summaries
- [x] Table Report Pending
- [x] Table Report Completed
- [x] Table Activity Progress
- [x] Table Organizations Provided Services

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/iMMAP/ngm-reportHub/pull/54
https://github.com/iMMAP/ngm-reportEngine/pull/23
