### ISSUE TITLE
Deactivated account still listed in the Forgot Password email

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#148]
If you go to the Forgot Password page and submit an email

If this email is associated with several accounts and some of the account is already deactivated
the email that being sent to reset the password is including the deactivated account

I think we should only send the link for username which in the active state
What do you think?

**Comment by fakhrihawari** [comment]
I prefer we still show it but with some information like this

<img width="587" alt="Screen Shot 2021-10-29 at 15 16 20" src="https://user-images.githubusercontent.com/12655589/139400475-a05e5aa9-8537-48a5-8810-a5ee8584f575.png">

**Comment by rafinkanisa** [comment]
That's a good idea

I think you could put the sentence as the following :
Cannot reset password. This account has been **DEACTIVATED**.

**Comment by fakhrihawari** [comment]
<img width="610" alt="Screen Shot 2021-11-18 at 14 24 04" src="https://user-images.githubusercontent.com/12655589/142370649-d45bb821-e91f-4882-9c9c-b1963876c295.png">

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportEngine/pull/27
