### ISSUE TITLE
Register using the same username is allowed

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#149]
When I check the database, I found that there are some duplicated username with different id
so I don't know how but it is possible to register using the same username with different organization

I think we shouldn't allow the user to take the same username for different account
Kindly fix this issue and please check :

- [x] Register page
- [x] My profile page > Is it possible to change the username using this page?

**Comment by fakhrihawari** [comment]
I have already tested and checked and that is not possible change  to username that already exists
