### ISSUE TITLE
RH ET Stock and Pipeline Report not visible

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#16]
Currently, the stock and pipeline report is not visible for below user :

BURWELL Christina
Meseret Damte
Selamawit Woldemichael
Sasha

Identify the problem and please make it visible for those users. The IM requested if possible make it visible for all the IOM teams.
Identify the risk for making it visible to all IOM teams member before changing it.

**Comment by fakhrihawari** [comment]
Please confirm if  this field is  their problem or not?
<img width="439" alt="Screen Shot 2021-05-07 at 09 41 45" src="https://user-images.githubusercontent.com/12655589/117390486-7b70d480-af18-11eb-91fe-a535e38b52e9.png">

And Please ask them the screenshot for this issue

**Comment by rafinkanisa** [comment]
So, based on the screenshot they give, probably the IOM members in Ethiopia can't see the same stock report page as the other member.
Below is Selam page
https://reporthub.org/desk/#/cluster/stocks/organization/5a1527d03f2de6f14de2ff9b/2021

while below is Christina Burwell's
https://reporthub.org/desk/#/cluster/stocks/organization/5b6420f61d7ff01d2f9776c8/2021

after checking, it has different organization_id even though all of them are from IOM
After getting clarification from Timur, we now know that :
in Ethiopia there is leftover of older reporting structure of one organization account per cluster, existing before 2019
in 2019 it has become one organization per country, and organizations updated only in Afghanistan

As this has a deeper issue, I will open another issue for the bigger picture. For this one, we'll only update for the IOM members only.

**Comment by fakhrihawari** [comment]
Scripts 
// **************** STOCK *********
db.getCollection("stock").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
        var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
        if (t) {
            d.organization_id = t._id.valueOf();
            db.getCollection("stock").save(d);
        } else {
            print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
        }
});

db.getCollection("stockwarehouse").find({ admin0pcode: "ET", organization_id: { $ne: null } , organization_tag: "iom"}).forEach(function (d) {

    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("stockwarehouse").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});

db.getCollection("stocklocation").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("stocklocation").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});

// check 
db.getCollection("stocklocation").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    print(d.organization_id)
})

// not sure should do this ornot 
db.getCollection("stockreport").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("stockreport").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});

// check 
db.getCollection("stockreport").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    print(d.organization_id)
})

// *************** Report *************
// 
    db.getCollection("beneficiaries").find({ admin0pcode: "ET", organization_id: { $ne: null } , organization_tag: "iom"}).forEach(function (d) {

        var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
        if (t) {
            d.organization_id = t._id.valueOf();
            db.getCollection("beneficiaries").save(d);
        } else {
            print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
        }
    });

db.getCollection("location").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("location").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});

db.getCollection("report").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("report").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});

// **************** PROJECT ************
// 
    db.getCollection("budgetprogress").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
        var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
        if (t) {
            d.organization_id = t._id.valueOf();
            db.getCollection("budgetprogress").save(d);
        } else {
            print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
        }
    });

db.getCollection("project").find({ admin0pcode: "ET", organization_id: { $ne: null } , organization_tag: "iom"}).forEach(function (d) {

    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("project").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});

db.getCollection("targetbeneficiaries").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("targetbeneficiaries").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});

db.getCollection("targetlocation").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("targetlocation").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
});


// *********** USER *********
    db.getCollection("user").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
        var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
        if (t) {
            d.organization_id = t._id.valueOf();
            db.getCollection("user").save(d);
        } else {
            print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
        }
    })

// USER LOGIN HISTORY
db.getCollection("userloginhistory").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("userloginhistory").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
})
// USER HISTORY
db.getCollection("userhistory").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    var t = db.getSiblingDB('ngmReportHub').getCollection("organization").findOne({ organization_tag: "iom", admin0pcode: "ET" })
    if (t) {
        d.organization_id = t._id.valueOf();
        db.getCollection("userhistory").save(d);
    } else {
        print('miss-L1', d.organization_id, d.organization_tag, d._id.valueOf())
    }
})

db.getCollection("userhistory").find({ admin0pcode: "ET", organization_tag: "iom" }).forEach(function (d) {
    print(d.organization_id)
})

// REMOVE Cluter_id and cluster attribute
db.organization.update({admin0pcode:"ET",organization_tag:"iom", cluster:{$exists:true}, cluster_id:{$exists:true}},{$unset:{cluster_id:"",cluster:""}})
// REMOVE IOM secondary record
db.organization.remove({admin0pcode:"ET",_id:ObjectId("5ff41b7e2d4951bf4392e752")})
db.organization.remove({admin0pcode:"ET",_id:ObjectId("5b6420f61d7ff01d2f9776c8")})
db.organization.remove({admin0pcode:"ET",_id:ObjectId("5aeaaf8cec394e5736b168e7")})
db.organization.remove({admin0pcode:"ET",_id:ObjectId("5aeaae2bec394e5736b168df")})

**Comment by fakhrihawari** [comment]
Need test and review on DEV for the result of the script
