### ISSUE TITLE
Add Cluster Observer Role Permission to the System

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#163]
Cluster Observer is a role that can only view & download the data in CLUSTER levels

Things you should check

- [x] My Team - User shouldn't be able to manage the other user permission role
- [x] My Admin - User should be able to send email notification
- [x] My Admin - User should be able to download all of the data in cluster levels
- [x] 5W Dashboard - User should be able to download all of the data in cluster levels
- [x] Monthly Progress - User shouldn't be able to edit any submitted report
- [x] Monthly Progress - User shouldn't be able to submit any to do report
- [x] Monthly Progress - User shouldn't be able to edit any submitted report grouped by locations
- [x] Monthly Progress - User shouldn't be able to submit any to do report grouped by locations

**Comment by fakhrihawari** [comment]
Link PR 
https://github.com/iMMAP/ngm-reportHub/pull/57
