### ISSUE TITLE
RH AF ESNFI Add Assessment Field

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#165]
The ESNFI cluster request to capture the assessment data with ReportHub

Below is the rule

- The input will appear only for Winterization project in ESNFI cluster
- Partners can find the input both in :
   - Section “Target Population” in “Activity Plan”
   - Each of the report
- The “Assessed Households” data can be downloaded using “Beneficiary Data as CSV” button in “My Admin” or “5W Dashboard” after filtering the sector to “ESNFI”

Things you should check

- [x] Activity Plan
- [x] Data download in Activity Plan
- [x] Monthly Progress
- [x] Biweekly Progress
- [x] Data download in Monthly Progress
- [x] Data download in Biweekly Progress
- [x] Data download in 5W Dashboard
- [x] Data download in My Admin

**Comment by fakhrihawari** [comment]
<img width="1080" alt="Screen Shot 2021-11-15 at 13 44 16" src="https://user-images.githubusercontent.com/12655589/141734695-5f7f14f0-419d-4922-abc6-4a554bd3f725.png">

**Comment by fakhrihawari** [comment]
Updated on DEV and PROD

Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/71
