### ISSUE TITLE
RH AF ESNFI Validation on Assessment Field

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#166]
Validate the assessment using the following rule :

- based on the previous period report that has been saved
- the “Activity”, “Description”, “Details” shall have the same information for successfully comparing to the previous period

Please see below case:
<img width="746" alt="Screen Shot 2021-12-02 at 18 06 37" src="https://user-images.githubusercontent.com/28089698/144410733-1d2ad6d4-0653-425f-bfec-88d23005458c.png">

If there’s someone would like to calculate the Total Assessed HH in Jan-Mar,  below case is the correct way to interpret the table.
 
Case A (using only the data from the last month report)
Project A = 50
Project B = 100
Total Assessed HH in Jan-Mar = 150

This is what ESNFI cluster has requested

**Comment by fakhrihawari** [comment]
<img width="1105" alt="Screen Shot 2021-11-15 at 13 47 12" src="https://user-images.githubusercontent.com/12655589/141735037-1272799f-8ffa-4836-a25d-cd015479494b.png">

Right now the validation is based only on previous report assessment households value and the value is always a positive number or greater than equal previous report assessment households.

If the previous report do not have assessment households, automatic will be set to 0

it considered valid if the value input by a user is >= previous report assessment households

the demo show in the picture above

**Comment by fakhrihawari** [comment]
Updated on DEV and PROD
https://github.com/iMMAP/ngm-reportHub/pull/71
