### ISSUE TITLE
RH AF ESNFI Change HH label name

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#170]
To avoid confusion with the "Assessed Households" input number, the ESNFI cluster requested to change the label name of "Households" to "Households Reached"

This should only apply to ESNFI activities in Afghanistan that has "Assessed Households" input appear.

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/iMMAP/ngm-reportHub/pull/71
