### ISSUE TITLE
Missing Last Login data for specific user

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#171]
Kindly check bugs as seen in the picture
<img width="1239" alt="Screen Shot 2021-12-02 at 18 14 14" src="https://user-images.githubusercontent.com/28089698/144411796-f09ebb44-0a3e-4f88-8b24-f28e853a930d.png">

**Comment by fakhrihawari** [comment]
Updated with this script:
db.user.find({ last_logged_in: { $exists: false } }).forEach(function (u) {
	if (!u.last_logged_in) {
		u.last_logged_in = u.updatedAt;
		db.user.save(u)
	}
})

**Comment by rafinkanisa** [comment]
Link PR https://github.com/iMMAP/ngm-reportHub/pull/78
