### ISSUE TITLE
RH NG WASH Blue Button could be clicked when not editing and reset total to 0

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#174]
There is a bug a found in Nigeria
Link : https://reporthub.org/desk/#/cluster/projects/report/6139f9e32cf321015fb74e90/615a67c25ec236fe641dbb3a

At first, there's 288 number in total
But, the Kit Detail is not expanded and I could clicked the blue button eventhough I'm not clicking edit report button in the submitted report as seen in below screenshot :
<img width="1680" alt="Screen Shot 2021-12-09 at 12 36 24" src="https://user-images.githubusercontent.com/28089698/145340472-af2cfe0c-dda2-46a6-bccd-5349822dbdd1.png">

Once the blue button is clicked, the number of total reset to 0 (see below video)

https://user-images.githubusercontent.com/28089698/145340525-2e8e0d0a-b708-40e0-83d8-6a6b0677073f.mov

Kindly check what the bug is and fix the issue

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/85
