### ISSUE TITLE
RH NG WASH Missing Details

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#175]
Link : https://reporthub.org/desk/#/cluster/projects/report/5de7bb1483fe98fb67deee2b/61060023d47931b96f4ff497

Total number is there but the details is missing as shown on below screenshots :
<img width="1680" alt="Screen Shot 2021-12-09 at 13 33 53" src="https://user-images.githubusercontent.com/28089698/145346251-de966878-bdc6-452e-bcf5-d016611d902b.png">

I've checked that the total is being automatically calculated after inputting the quantity, so, how did they put those numbers?

Kindly identify the problem and fix the issue

**Comment by rafinkanisa** [comment]
The reason might be that when partners removing the details, the system didn't reset the total to 0
Currently, I'm asking to the focal person in Nigeria on what the expected behaviour of the system should be

**Comment by rafinkanisa** [comment]
Updates from the focal person in Nigeria is to reset to 0 when the details is removed.

Kindly proceed.

**Comment by fakhrihawari** [comment]
Already updated 
link PR:
https://github.com/rafinkanisa/ngm-reportDesk/issues/70
