### ISSUE TITLE
RH AF Protection Add Blank Report in the Data Download

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#177]
The protection cluster request to include also the blank report in the data download.
They need the locations of those partners
I know that we're using different collections to extract data

Could you have a way to enable the blank report to be in the data download only for protection cluster?

Checklist :

- [x] The header column should be the same as in Beneficiaries Data CSV

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/iMMAP/ngm-reportHub/pull/88
