### ISSUE TITLE
RH AF Biweekly couldn't download CSV in Report which grouped by province

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#179]
Couldn't download the CSV in the biweekly report page that grouped by province

Link : https://reporthub.org/desk/#/cluster/projects/group/619f2fecfc2d88391504d67f/619f2fecfc2d88391504d689

Also, the download button tooltip showing monthly, not biweekly. Check if this a mistake
<img width="1680" alt="Screen Shot 2021-12-09 at 19 01 15" src="https://user-images.githubusercontent.com/28089698/145393620-4444ff3e-8b05-47c6-8c41-91e76747ad11.png">

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/89
