### ISSUE TITLE
RH ET Clean Organization

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#18]
In Ethiopia there is leftover of older reporting structure of one organization account per cluster, existing before 2019
in 2019 it has become one organization per country, and organizations updated only in Afghanistan

As a reference please see the issue here
https://github.com/pfitzpaddy/ngm-reportDesk/issues/127

We'll have to clean organization data in Ethiopia
You can share the script here

**Comment by dodiws** [comment]
[This](https://github.com/rafinkanisa/ngm-reportDesk/files/7683197/find_refs_to_duplicate_orgs.js.zip) is script to find collections in `ngmHealthCluster` with references to duplicate `organization` in `ngmReportHub`, delete the duplicates, then update the references.

Usage:

    // adjust admin0pcode and lt_report_year variables in 'base match' section (line 52 or so)

    // open mongo shell with find_refs_to_duplicate_orgs.js script
    mongo localhost:27017/ngmHealthCluster find_refs_to_duplicate_orgs.js --shell

    // show duplicate organizations
    run_query_func(find_duplicate_orgs_query)

    // delete duplicate organizations
    delete_duplicate_organizations()

    // check delete result
    run_query_func(find_duplicate_orgs_query)

    // show references to duplicate organizations
    show_refs_to_duplicate_orgs()

    // update references to duplicate organizations
    update_refs_to_duplicate_orgs()

    // check update result
    show_refs_to_duplicate_orgs()

**Comment by fakhrihawari** [comment]
After test in my local there's some error in this script
error:
update org ref using _id: 59f1ba4543cd76e142ea9348
2021-12-08T07:24:53.910+0000 E QUERY    TypeError: Property 'updateMany' of object ngmHealthCluster.beneficiaries is not a function
    at find_refs_to_duplicate_orgs.js:150:50
    at Object.DBQuery.forEach (src/mongo/shell/query.js:414:9)
    at find_refs_to_duplicate_orgs.js:145:18
    at Array.forEach (native)
    at update_refs_to_duplicate_orgs (find_refs_to_duplicate_orgs.js:141:21)
    at (shell):1:1 at find_refs_to_duplicate_orgs.js:150

**Comment by fakhrihawari** [comment]
Already run the fixed script and run it on PROD Server
