### ISSUE TITLE
RH AF API differs from download

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#181]
When using the API to download from all cluster from Nov-Dec 2021, it only has 3500 rows while when I directly download from the website, it has 3774 rows (extracted at Dec 16, 2021). I need to share the data from 2020-2021

My first suspect is that the biweekly is not included in the API. Is this really the correct way?

API :
https://reporthub.immap.org/api/cluster/indicator?adminRpcode=emro&admin0pcode=af&admin1pcode=all&admin2pcode=all&cluster_id=all&organization_tag=all&start_date=2021-11-01&end_date=2021-12-31&indicator=beneficiaries&beneficiaries[]=all&ocha=true&csv=true&reportname

**Comment by fakhrihawari** [comment]
Already fix it 
Link PR:
https://github.com/iMMAP/ngm-reportEngine/pull/38
