### ISSUE TITLE
RH AF ESNFI Assessment Validation ver 2

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#182]
After completing this issue https://github.com/rafinkanisa/ngm-reportDesk/issues/166, the ESNFI cluster comes back to us and requested to change the validation rule.

At the moment, they wanted to validate also based on location, Beneficiary, HRP Beneficiary, Category & Type.

I think we've done this previously? Kindly put it on the DEV then I'll check when I back from leave

**Comment by fakhrihawari** [comment]
already on DEV Server

**Comment by rafinkanisa** [comment]
I've checked and it's still not validated based on Type. Kindly update

<img width="1137" alt="Screen Shot 2022-01-03 at 15 59 09" src="https://user-images.githubusercontent.com/28089698/147913631-19b6fb59-2b5d-409c-9a8b-b0dd86131630.png">

**Comment by fakhrihawari** [comment]
Updated on PROD
Link PR
https://github.com/iMMAP/ngm-reportHub/pull/96
