### ISSUE TITLE
RH AF ESNFI Remove Assessment Validation

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#183]
As a temporary solution while waiting for Fakhri back from his leave

The ESNFI cluster requested to remove the validation of Assessed HHs in the system.
Kindly read the issue https://github.com/rafinkanisa/ngm-reportDesk/issues/166 to have a better understanding.

They hope it could be finished immediately.

**Comment by sud0su** [comment]
done, the updated code has been pushed as a PR(Pull request) of the ngm-reportHub repo, and @dodiws has tested the code and merged it to the main repo.

[Link PR](https://github.com/iMMAP/ngm-reportHub/pull/90)
