### ISSUE TITLE
RH AF ESNFI Biweekly

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#184]
At the moment, we're showing the 2 biweekly report periods once the system enters the new month.
Would it be possible to make the 2nd report period available ONLY after 16 of the month?

The ESNFI cluster is requesting this to minimize the partners submitting the wrong report

**Comment by fakhrihawari** [comment]
we have two options:
1. filtered from back end 
2. from UI

**Comment by fakhrihawari** [comment]
from UI
![Screen Shot 2021-12-28 at 15 07 40](https://user-images.githubusercontent.com/12655589/147543782-788ea0dc-6a7a-4c0f-8788-8336214a198f.png)

**Comment by fakhrihawari** [comment]
After trying and some thought, I decide to filter from BE because is more efficient

**Comment by fakhrihawari** [comment]
Already on PROD
Link PR
https://github.com/iMMAP/ngm-reportEngine/pull/39
