### ISSUE TITLE
RH AF WASH Person with Disabilities bug

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#186]
I remember that we have enabled the category of person with disabilities in WASH Cluster. For some reason, I could see it like below.
<img width="1127" alt="Screen Shot 2021-12-23 at 06 53 28" src="https://user-images.githubusercontent.com/28089698/147178026-26fe4614-8780-46a6-93e3-a04156c8dd1a.png">

<img width="1124" alt="Screen Shot 2021-12-23 at 09 35 36" src="https://user-images.githubusercontent.com/28089698/147179324-cf91b544-d121-47d3-befa-ce3f5abdaae7.png">

<img width="1126" alt="Screen Shot 2021-12-23 at 09 35 59" src="https://user-images.githubusercontent.com/28089698/147179350-94afeb14-4147-4576-8440-5cc58189394b.png">

Identify the issue, and please kindly fix the bugs

**Comment by fakhrihawari** [comment]
Please check the activity column total_pwd for each activity that needs to use "Person with disabilities".
I briefly check 

![Screen Shot 2021-12-27 at 09 27 34](https://user-images.githubusercontent.com/12655589/147428248-af46ca59-ad2d-49d0-ba01-0f3219c02309.png)

some activities set 0 in column total_pwd
