### ISSUE TITLE
RH AF Showing different total beneficiary

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#193]
In the screenshots below, the SADD group has different total number with the total beneficiaries calculated automatically by the system
<img width="1143" alt="Screen Shot 2022-01-04 at 10 56 56" src="https://user-images.githubusercontent.com/28089698/148007767-e299021e-3ea8-49d9-bfbe-3e305c1412e5.png">

<img width="1134" alt="Screen Shot 2022-01-04 at 10 57 10" src="https://user-images.githubusercontent.com/28089698/148007782-1948a038-4dd4-4f89-a669-9c09c3187b0d.png">

Link :
https://reporthub.org/desk/#/cluster/projects/report/5faa586b399d8e9d34eeff5a/612edea27fd758f36030d1ff
Location : Kunar, Dara-e-Pech, Senzia CHC

Not just this one, many other reports have the same issue
Kindly identify the issue and fix

**Comment by fakhrihawari** [comment]
To update script
db.beneficiaries.find({ report_year: 2021, admin0pcode: "AF" }).forEach(function (beneficiary) {
  if ((beneficiary.boys + beneficiary.men + beneficiary.elderly_men + beneficiary.girls + beneficiary.women + beneficiary.elderly_women) !== beneficiary.total_beneficiaries){
    beneficiary.total_male = 0;
    beneficiary.total_female = 0;
    beneficiary.total_beneficiaries = 0;

    beneficiary.total_male += ((beneficiary.boys === null || beneficiary.boys === undefined || beneficiary.boys === NaN || beneficiary.boys < 0 || beneficiary.boys === '') ? 0 : beneficiary.boys) +
      ((beneficiary.men === null || beneficiary.men === undefined || beneficiary.men === NaN || beneficiary.men < 0 || beneficiary.men === '') ? 0 : beneficiary.men) +
      ((beneficiary.elderly_men === null || beneficiary.elderly_men === undefined || beneficiary.elderly_men === NaN || beneficiary.elderly_men < 0 || beneficiary.elderly_men === '') ? 0 : beneficiary.elderly_men);

    beneficiary.total_female += ((beneficiary.girls === null || beneficiary.girls === undefined || beneficiary.girls === NaN || beneficiary.girls < 0 || beneficiary.girls === '') ? 0 : beneficiary.girls) +
      ((beneficiary.women === null || beneficiary.women === undefined || beneficiary.women === NaN || beneficiary.women < 0 || beneficiary.women === '') ? 0 : beneficiary.women) +
      ((beneficiary.elderly_women === null || beneficiary.elderly_women === undefined || beneficiary.elderly_women === NaN || beneficiary.elderly_women < 0 || beneficiary.elderly_women === '') ? 0 : beneficiary.elderly_women);

    beneficiary.total_beneficiaries += beneficiary.total_male + beneficiary.total_female;

    db.beneficiaries.save(beneficiary)
  }
})

and for preventive action before saving report , need to recalculate so this won't happen again

**Comment by fakhrihawari** [comment]
For prevention, we add a function to recalculate the beneficiaries before saving the report
Link PR:
iMMAP/ngm-reportHub#97
