### ISSUE TITLE
RH AF Downloaded file name is incorrect

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#194]
When I download the specific monthly report, the file name is written :
january_2022_Integrated_lifesaving_Health,_Nutrition,_Protection_and_WaSH_response_in_the_conflict-affected_areas_of_Afghanistan’s_Eastern_Region_extracted-2022-01-04T1033

Link :
https://reporthub.org/desk/#/cluster/projects/report/5faa586b399d8e9d34eeff5a/612edea27fd758f36030d1ff

I downloaded the September 2021 report, so it should have been september_2021 isn't it?
Kindly identify the issue and fix

**Comment by fakhrihawari** [comment]
Already fixed
Link PR:
https://github.com/iMMAP/ngm-reportHub/pull/97
