### ISSUE TITLE
RH AF Update Biweekly Guidance

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#195]
As a following action to revise the validation rule, We'll need to update the user guide put on the system.
Currently, the document is still being reviewed. Once approved, kindly update on the system.

**Comment by rafinkanisa** [comment]
I just received the document. Please upload it to the system

[ReportHub Assessed Household Guidance.pdf](https://github.com/rafinkanisa/ngm-reportDesk/files/7819599/ReportHub.Assessed.Household.Guidance.pdf)

**Comment by rafinkanisa** [comment]
The space is somewhat big. May you please adjust according to resolution 1920 x 1080 also?

![image](https://user-images.githubusercontent.com/28089698/148342721-bd9724db-0e07-4afc-8f54-2143eaa1ed5e.png)

**Comment by fakhrihawari** [comment]
On it

**Comment by fakhrihawari** [comment]
Updated on PROD
Link PR: 
https://github.com/iMMAP/ngm-reportHub/pull/98
https://github.com/iMMAP/ngm-reportHub/pull/99
