### ISSUE TITLE
AF Duplicate organization name on ReportHub DB

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#2]
Clean up the organization data in user collections.
It appears that some organizations would appear 2 times when querying in user collections.
Below are organization needed to check :

- Afghanaid
- Americares Foundation
- Mission East

Identify first the reason. Apply the fix as per analysis on how each of that happens.

**Comment by fakhrihawari** [comment]
Updated on PROD
