### ISSUE TITLE
Put filter activity on Copy Previous Month

### ISSUE THREAD

**Issue by fakhrihawari** [rafinkanisa/ngm-reportDesk#20]
Some Activity that already end still can be copy from previous month

**Comment by rafinkanisa** [comment]
consider the reference here https://github.com/drfaustusfade/ngm-reportDesk/issues/56

**Comment by fakhrihawari** [comment]
<img width="737" alt="Screen Shot 2021-05-25 at 09 16 55" src="https://user-images.githubusercontent.com/12655589/119429913-0126b980-bd3a-11eb-80ba-094dffcaafc3.png">

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/151

**Comment by fakhrihawari** [comment]
Final mockup

<img width="1359" alt="Screen Shot 2021-05-27 at 16 37 08" src="https://user-images.githubusercontent.com/12655589/119949848-79a0ab00-bfc4-11eb-8063-d335734a5b7d.png">

**Comment by rafinkanisa** [comment]
Well done.
This will prompt the user to save the monthly report if they have existing activities which have been defined as ended activities by the cluster.
This will also let the user know which activities should be changed/removed as the system didn't removed them automatically.
