### ISSUE TITLE
RH ET Cash for Rent Update

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#21]
Change the following:

output_objective_id, 
output_objective, 
sector_objective_id, 
sector_objective_name, 
sector_objective_description

for activity_description_id = cash_for_rent (row 14)
https://docs.google.com/spreadsheets/d/1YqPza47XEacw-5sxTYJe4A2ZH8Qoi-ofTKRHsqeF-uU/edit#gid=1340960157

Also please update the stored data in database accordingly.

**Comment by fakhrihawari** [comment]
QUERY

db.getCollection('beneficiaries').update( {admin0pcode:"ET",activity_description_id:"nfi_kit"},{ $set:{activity_description_id :"nfi_kit_in_kind"}}, {multi: true})

db.getCollection('targetbeneficiaries').update( {"admin0pcode":"ET","activity_description_id":"nfi_kit"},{$set:{activity_description_id :"nfi_kit_in_kind"}}, {multi: true})


db.getCollection('targetbeneficiaries').update({"admin0pcode":"ET","activity_description_id":"cash_for_rent"},{$set:{
"sector_objective_id":"CO1.3.2",
"sector_objective_name":"Cluster Objective 1.3.2",
"sector_objective_description":"1.3.2 Number of displacements affected population that received in-kind or cash for emergency shelter assistance to improve physical protection and to reduce overcrowding (Cash for Rent activities)"
}},{multi:true})

db.getCollection('beneficiaries').update({"admin0pcode":"ET","activity_description_id":"cash_for_rent"},{$set:{
"sector_objective_id":"CO1.3.2",
"sector_objective_name":"Cluster Objective 1.3.2",
"sector_objective_description":"1.3.2 Number of displacements affected population that received in-kind or cash for emergency shelter assistance to improve physical protection and to reduce overcrowding (Cash for Rent activities)"
}},{multi:true})

db.getCollection('beneficiaries').find({"admin0pcode":"ET","activity_description_id":"cash_for_rent"})
db.getCollection('targetbeneficiaries').find({"admin0pcode":"ET","activity_description_id":"cash_for_rent"})
db.getCollection('beneficiaries').find({"admin0pcode":"ET","activity_description_id":"nfi_kit"})
db.getCollection('targetbeneficiaries').find({"admin0pcode":"ET","activity_description_id":"nfi_kit"})
