### ISSUE TITLE
Moving Beneficiary Types to API

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#26]
Move the beneficiary types to API. Applied this to the HRP also.

See reference 
https://github.com/drfaustusfade/ngm-reportDesk/issues/45
https://github.com/drfaustusfade/ngm-reportDesk/issues/66

**Comment by fakhrihawari** [comment]
Still working on Beneficiarytypes
need to do testing on DEV 

And for HRP will be done after beneficiarytypes

**Comment by fakhrihawari** [comment]
Link HRP Beneficiary Types List data: https://docs.google.com/spreadsheets/d/1zNAVor_45CAVaxB8cdkSGVLm68PdZMtPI3WdAhMa55k/edit#gid=0

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/171
https://github.com/drfaustusfade/ngm-reportEngine/pull/32

Updated on DEV and PROD
