### ISSUE TITLE
Adding Cumulative of Beneficiaries

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#28]
This is only an idea from partners to add the sum of beneficiaries in the Activity Plan page section Target Beneficiaries.
It is suggested to be the same as in the Monthly Progress
So, no new input showing, only showing this as labels

See picture as reference
![image](https://user-images.githubusercontent.com/28089698/117892258-93fb3900-b2e2-11eb-882b-0cfb376c34cf.png)

**Comment by fakhrihawari** [comment]
https://github.com/fakhrihawari/ngm-reportHub/tree/adding-cumulative-beneficiaries

**Comment by fakhrihawari** [comment]
<img width="1224" alt="Screen Shot 2021-06-29 at 13 14 00" src="https://user-images.githubusercontent.com/12655589/123746499-ec5eb800-d8db-11eb-8c72-51bbb350f3b4.png">

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/179

Updated on DEV and PROD
