### ISSUE TITLE
Bugs on Updating Organization via Profile Page

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#3]
Identify possible bugs when changing organization using the dropdown in the profile page.

For some reason, the organization_name and organization_tag attribute doesn't change even after the user successfully changing the organization. This spotted while looking at the database. Changing organization is possible in several user roles.

**Comment by fakhrihawari** [comment]
the profile page has a feature to change organization, but that already disabled and not yet active till now.

**Comment by rafinkanisa** [comment]
I am seeing several cases which might be caused by this. Below is one of the example. This happens to one user that just registered on 2021 in ET. The user email is f.beyene@ethiopia.dorcas.org

There is org_id in organization ngmReportHub with org_tag=iom but org=DAE using below query
db.getCollection("organization").find({admin0pcode:"ET", organization_tag:"iom"})

DAE = Dorcas AID Ethiopia

If we search DAE, in collection organization ngmReportHub org_id = 5ff41b7e2d4951bf4392e752

but, in collection user ngmReportHub, org_id = 5fe09158e28ddfce7c1ab0a6

in collection userloginhistory ngmReportHub, org id = 5ff41b7e2d4951bf4392e752

if we search in userloginhistory of org id = 5fe09158e28ddfce7c1ab0a6 , it's showing 0 result

currently, org_tag for user with email f.beyene@ethiopia.dorcas.org is aoad but the organization = Dorcas Aid Ethiopia

**Comment by rafinkanisa** [comment]
More explanation about this....

5fe09158e28ddfce7c1ab0a6 this is Dorcas Aid Ethiopia, organization( abbreviation ) attribute should be DAE, but name tag type not on organization and user collections ( also there are 3 entries on beneficiaries, so that project related collections should also be updated  )
5ff41b7e2d4951bf4392e752 this is also DAE, looks like the user was registering by for some error users was not created or iom deleted that user as there was bug with tag assignment, as there is entry in userloginhistory but no user in user collection, so i would say that organization should be removed, that is the same user, there is one user for one organization first time registered in December ( also with wrong name tag attribute values 5fe09158e28ddfce7c1ab0a6 ), then the user tried to register again, and then later in the month again which is the current user

I can see there exist other similar data bugs, so that ET and SO should be checked carefully
