### ISSUE TITLE
Modal Preview on Organization Page

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#30]
Enable the modal preview in the list of organization page.
This is something we talked during the training with Timur due to something is not working/confusing in the organization page.

See reference https://github.com/drfaustusfade/ngm-reportDesk/issues/73

**Comment by fakhrihawari** [comment]
Link PR : https://github.com/drfaustusfade/ngm-reportHub/pull/131/files
updated on DEV and PROD
