### ISSUE TITLE
CLUSTER User Notification

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#32]
This is a suggestion from partners to have a notification.
It would be good to enable the CLUSTER user sending notifications to partners who haven't submitted their monthly report yet.

See reference https://github.com/drfaustusfade/ngm-reportDesk/issues/52

**Comment by rafinkanisa** [comment]
Put comma at the end of the name "Hi ....,"

minor changes at below sentences:
Please submit **month year** report for Project **project_title** as requested by **name_requester**.

<img width="602" alt="Screen Shot 2021-08-18 at 14 55 22" src="https://user-images.githubusercontent.com/28089698/129860301-d22b4dba-cfb3-48e3-802e-3cd0d49d4f78.png">

**Comment by fakhrihawari** [comment]
<img width="809" alt="Screen Shot 2021-08-19 at 14 21 28" src="https://user-images.githubusercontent.com/12655589/130025575-762a5776-3e0f-45c7-83ac-fd58bd55afb6.png">

**Comment by fakhrihawari** [comment]
<img width="655" alt="Screen Shot 2021-08-19 at 14 33 37" src="https://user-images.githubusercontent.com/12655589/130027228-053601a9-92b7-4ae3-b605-e47846845d92.png">

**Comment by fakhrihawari** [comment]
After revision
<img width="604" alt="Screen Shot 2021-08-30 at 13 41 12" src="https://user-images.githubusercontent.com/12655589/131296455-a6ca92f3-67e7-4789-8f0e-79331f343c24.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

**Comment by rafinkanisa** [comment]
Could you update this on DEV?

**Comment by rafinkanisa** [comment]
Change the table header from "Send Email" to "Email Reminder"
Is it possible to make the button become inactive for 24h after clicked?

Why did you put different button text in page 1 & 2 ?

page 1 :
<img width="115" alt="Screen Shot 2021-09-15 at 15 03 57" src="https://user-images.githubusercontent.com/28089698/133394948-e9554035-12d0-464f-8f78-6c9570b1b5dc.png">

page 2 :
<img width="138" alt="Screen Shot 2021-09-15 at 15 04 12" src="https://user-images.githubusercontent.com/28089698/133394986-283e14d4-6083-40cd-a3a9-de64ad462285.png">

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
