### ISSUE TITLE
User Last Login

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#36]
Adding last logged in attribute

See Reference https://github.com/drfaustusfade/ngm-reportDesk/issues/7

**Comment by fakhrihawari** [comment]
branch :
https://github.com/fakhrihawari/ngm-reportHub/tree/add-atribute-last-loggedin
https://github.com/fakhrihawari/ngm-reportEngine/tree/add-lastlogged-fo-user

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportEngine/pull/35
Updated on DEV and PROD
