### ISSUE TITLE
Add New Activity for Health Cluster

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#38]
Add new activity in health cluster under Primary health care - Number of physical rehabilitation session.

**Comment by fakhrihawari** [comment]
added on row 943

**Comment by fakhrihawari** [comment]
<img width="1210" alt="Screen Shot 2021-05-24 at 11 25 21" src="https://user-images.githubusercontent.com/12655589/119296233-c57ce880-bc82-11eb-895e-3a505bcb4f75.png">
