### ISSUE TITLE
5W Dashboard Filter not showing

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#43]
In 5W Dashboard, we have filters located on the left side. For some reason, after filtering the activity, the list in the activity description filter only showing 1 list although it should showing more than 1.

For example, below is the filter looks like after choosing Protection in Cluster and GBV in Activity.
![image](https://user-images.githubusercontent.com/28089698/121005307-e0d71000-c7b9-11eb-9ac4-e125728bd76f.png)

Below is the available list in Activity Description showing in the dropdown list for GBV from Activity Plan Page
![image](https://user-images.githubusercontent.com/28089698/121005588-2b588c80-c7ba-11eb-896d-6ed070a38729.png)

Identify the reason and please fix this bug so we could use the filter.

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportEngine/pull/29
https://github.com/drfaustusfade/ngm-reportHub/pull/154

updated on DEV and PROD
