### ISSUE TITLE
Add new Stock Type in Stock & Pipeline Report

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#45]
Add new stock type in Stock Report as below :

1. Non-Food Items (NFI) In-Kind
2. Cash for NFIs (Non-Food Items)
3. ES Kit

**Comment by fakhrihawari** [comment]
Non-Food Items (NFI) In-Kind
Non-Food Items (NFI) In-Cash
Non-Food Items (NFI) Mixed 
Emergency Shelter Kit
Emergency Shelter Construction

**Comment by fakhrihawari** [comment]
updated on DEV and PROD
