### ISSUE TITLE
Profile Page show Blanks

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#46]
For some reason, the profile page showing a blank page. This only applied to this user only.
Below is the link page
https://reporthub.org/desk/#/profile/Shacdohealth&nutrition%20officer

Screenshot as below
![image](https://user-images.githubusercontent.com/28089698/121501227-3b19e000-ca09-11eb-83b4-12d1ca295982.png)

Please identify the reason and do the fix. Thank you.

**Comment by rafinkanisa** [comment]
Turns out this is because the user has a username with & character.
The links to the profile page not encoded to %26 therefore the page is obsolete and shows a blank page.

**Comment by fakhrihawari** [comment]
Fix it on PR
https://github.com/drfaustusfade/ngm-reportHub/pull/156

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/160

Updated on DEV and PROD
