### ISSUE TITLE
Inconsistency Data in Organization

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#47]
For some reason, there's an inconsistency data. So, user could register and pick an organization that was not listed in the system but the organization_name and organization_tag is stored in the system list.

Identify the reason and please do the fix.

**Comment by rafinkanisa** [comment]
Turns out it is because of the autocomplete functionality on the register page.
So, user could type their organization after choosing one of the organizations in the dropdown. The "next" button isn't disabled after doing this. Making users allowed to type.

**Comment by fakhrihawari** [comment]
Updated on DEV and PROD
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/158
