### ISSUE TITLE
No Notification on Profile Page after Update

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#48]
There is a bug when I tried to change my username. After clicking "Update" button, it doesn't notified whether the update is success or not.

For details, you can see below video :
https://user-images.githubusercontent.com/28089698/121835336-3ef47d80-ccfb-11eb-8d7e-1e8c7c19c54e.mov

Below is the error showing up :
![image](https://user-images.githubusercontent.com/28089698/121835549-c641f100-ccfb-11eb-9c23-8894a70293f6.png)

Please fix the bugs by notify the user if the update process is failed.

**Comment by fakhrihawari** [comment]
https://github.com/drfaustusfade/ngm-reportHub/pull/160

Updated on DEV and PROD
