### ISSUE TITLE
Update Profile linked to 2 different profile page

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#49]
After successfully updating my username, when I go to my team, the username shown in the table has changed. If I clicked it, it goes to the correct link : https://reporthub.org/desk/#/profile/rafinkanisa_cxb
![image](https://user-images.githubusercontent.com/28089698/121836331-6a786780-ccfd-11eb-98d0-076db7ab70ad.png)

But, if I click menu > my home > my profile
It will redirect me to the old profile link : https://reporthub.org/desk/#/profile/rafinkanisa
![image](https://user-images.githubusercontent.com/28089698/121836513-c511c380-ccfd-11eb-9d50-4dee92cb7f71.png)

Strangely the two links works. And in the menu, my username hasn't been changed to the new one. You can see rafinkanisa in the menu on below screenshot :
![image](https://user-images.githubusercontent.com/28089698/121836598-f8545280-ccfd-11eb-847d-8e539be5bd33.png)

This could make confusion when another user try to update their username.
Please identify the reason and do the fix. Thank you.

**Comment by fakhrihawari** [comment]
https://github.com/drfaustusfade/ngm-reportHub/pull/160

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/160

Updated on DEV and PROD
