### ISSUE TITLE
Update CVA Activities in Protection Cluster

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#5]
We need to update several activities to make it in line with the cluster needs.

Enable SADD inputs on
- [x] Vulnerable HH received one-off cash for protection activity
Enable the SADD as in mpc form

Enable CVA inputs 
- [x] Provision of cash as a component of the Case Management services to children and adolescents at risk
- [x] Individual Protection Assistance cash or in-kind ( in )
For now, we will leave the grant_type metadata as blanks and updated it later on once we got confirmation from CPiE. The transfer_type will be for Individuals only.

These updates should be ready before the next reporting period. Please also make sure that we will don't have any issue with the report that has been submitted in Q1 (Jan - Mar 2021). And also make sure no bugs are found when the old report data (such as number of beneficiaries data and cash amount value) being updated.

**Comment by fakhrihawari** [comment]
> We need to update several activities to make it in line with the cluster needs.
> 
> Enable SADD inputs on
> 
> * [x]  Vulnerable HH received one-off cash for protection activity
>   Enable the SADD as in mpc form
> 
> Enable CVA inputs
> 
> * [x]  Provision of cash as a component of the Case Management services to children and adolescents at risk
> * [x]  Individual Protection Assistance cash or in-kind ( in )
>   For now, we will leave the grant_type metadata as blanks and updated it later on once we got confirmation from CPiE. The transfer_type will be for Individuals only.
> 
> These updates should be ready before the next reporting period. Please also make sure that we will don't have any issue with the report that has been submitted in Q1 (Jan - Mar 2021). And also make sure no bugs are found when the old report data (such as number of beneficiaries data and cash amount value) being updated.

Note: activities.csv
Enable SADD row => 689
Enable CVA inputs row => 612, 686

**Comment by rafinkanisa** [comment]
As agreed with the Protection Cluster IMO, please do the followings :

- [x] Enable all possible options in the grant_type metadata for the CVA
- [x] Split Individual Protection Assistance cash or in-kind ( in ) into 2 different activities

Identify the last report submitted for Individual Protection Assistance cash or in-kind ( in ) activities then we can disable it after that date. This is beneficial for historical data since we already have partners submitting the reports for Q1 around 130 activities. Therefore, starting from the identified month I have mentioned before, we won't see this activity anymore, and partners can use the distincted activity instead.

And also please sort it alphabetically, so we can see the new 2 activities side by side

Previously, we have made In-kind units only showing on in-kind options only but the IM also wants to hide/disable the transfer value and transfers therefore we recommend to split the activities instead.

The defined in-kind units options are “unit" & "service". Please make the modification accordingly.

**Comment by rafinkanisa** [comment]
After we split the IPA into 2 activities, the Protection IMO reach out to us and request that the naming should be as following :

- Individual Protection Assistance (cash)
- Individual Protection Assistance (in-kind)

Check if there are already partners that has already reported this activity. If no partners has reported this, then rename accordingly.
As for in-kind activities, please remove the transfer type and the grant type as it is not needed.
Also if possible, make the implementation modality automatically selected the in-kind option as that only has 1 option available...

What if we remove the implementation modality but keep the units enabled? Is it possible?

Lastly, don't forget to sort the options alphabetically because when I saw in the IM computer machine, it is still jumbled.

Please also change the static text that saying "Transfer Value/amount: Please enter the amount per HOUSEHOLD (HH) per Transfer" to "Transfer Value/amount: Please enter the amount per INDIVIDUAL per Transfer" only for IPA activities.

**Comment by rafinkanisa** [comment]
There are some partners suggesting to enable the cumulative input amount of cash

Although this needs consent from the CVWG Coordinator, let's put it in the Refactoring CVA plan.
