### ISSUE TITLE
RH NG Add New Activity

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#52]
Please add a new activity for the WASH sector in Nigeria with below structure:
Activity -> Water ->Description -> Operation and Mentainance -> Details -> Water Chlorination (new activity)

Details for Chlorination should be quantity (m3/ per month) and this will be used to estimate the number of beneficiaries just like in fuel provision for water.

Start date : Jan 2021

**Comment by fakhrihawari** [comment]
activities.csv row 139

**Comment by fakhrihawari** [comment]
<img width="1183" alt="Screen Shot 2021-06-23 at 08 37 59" src="https://user-images.githubusercontent.com/12655589/123021997-44d71680-d3ff-11eb-8654-7cce85aae78a.png">

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/173

Updated on DEV and PROD
