### ISSUE TITLE
Bugs while choosing organization in Register page

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#54]
Currently, RH have organization list that administers to a country.
For some reasons, I could register using organization that's supposed to be not active in a country.

How do I create the bugs :
First, I choose the organization : CARE Nigeria
Then I choose the country : Afg
Fill up the rest of the form

I could see the active user from this organization is 9. Those users might come from CARE International organization.
In the activity plan page, the project I can see is from CARE International and CARE International in Afghanistan.

CARE Nigeria was supposed to be only active in nigeria only
CARE Nigeria and CARE International has the same org_tag = care

Please also make the organization sorted alphabetically.

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/181

Updated on DEV and PROD
