### ISSUE TITLE
RH AF Bugs on Beneficiary Types

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#57]
The below list is missing from the Beneficiary Types dropdown list although the end date hasn't been defined. 

- Conflict Affected
- Protracted IDPs
- Underserved Community

Partner can't found those activity after selecting "Trauma Care, FATP - Stabilization & Referrals ( Conflict )" activity.

Kindly check why this bug occurred and please do the fix of this bugs as soon as possible.

**Comment by rafinkanisa** [comment]
They also report that on the previous months report of "Primary Health Care - OPD Consultation" activity, the beneficiary types are changing from "Underserved Community" to "Access to Services" even though they didn't choose it previously.

**Comment by fakhrihawari** [comment]
The problem, there is some beneficiary_type_id  with the same value but different beneficiary_type_name for the different clusters,
we use the function to remove duplicates based on key attributes in list turn out it remove it from the list
how to solve:
We add cluster as a parameter to filter beneficiary type list
But Already fix that issue with this PR
Link PR for this:

https://github.com/drfaustusfade/ngm-reportHub/pull/188/files

https://github.com/drfaustusfade/ngm-reportHub/pull/190/files

updated on DEV and PROD

**Comment by rafinkanisa** [comment]
Turns out that the "underserved community" beneficiary type, is not listed in Health cluster. So, they didn't have this beneficiary type on their list.

In the previous months, the system has a bug. Therefore, the partners could choose "underserved community" beneficiary type under "Primary Health Care - OPD Consultation" activity which suppose shouldn't have happened.

Need suggestion from the Health Cluster side whether to enable this beneficiary option or not.
