### ISSUE TITLE
RH ET ESNFI Program Coordinating Partners

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#58]
It was requested to altered the "Programme Partners" to "Program Coordinating Partners" in Project Plan page.
The following should also be added to the list of program coordinating partners :
RRF/IOM, SWAN, UNHCR, IOM, CWW, CCM, Christian Aid, ERM/IRC, IRC, CRS

Alter the name to all associated with it (including the header title in the data download). Implement this only to ESNFI Cluster in Ethiopia.

**Comment by fakhrihawari** [comment]
Link PR :

https://github.com/drfaustusfade/ngm-reportHub/pull/193
https://github.com/drfaustusfade/ngm-reportEngine/pull/39

updated on DEV and PROD

**Comment by rafinkanisa** [comment]
Screenshot of the project plan :
<img width="1121" alt="Program Coord  Org" src="https://user-images.githubusercontent.com/28089698/125236480-3ef19880-e30e-11eb-8367-8a18dc13b6af.png">

Screenshot of the list :
<img width="553" alt="List Program Coord  Org" src="https://user-images.githubusercontent.com/28089698/125236492-46b13d00-e30e-11eb-884f-95dece64c6c3.png">
