### ISSUE TITLE
Clean organizations list

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#6]
For some reason list in organizations.csv has several duplicate organization_tag with different organization_name. Clean up this data in the database. Currently, there are at least around 66 duplications have been identified (could be less).

Identify first how the fix will affect other data. Apply the fix for all related collections.

**Comment by fakhrihawari** [comment]
Link cleaned organization
https://docs.google.com/spreadsheets/d/1uE9qGDXG2VxvFWK-2lxpjR3oP9iAcTwAk1jP4T3EtWg/edit#gid=0

note : 
cell with blue color indicate that the row is modified
cell with red color indicate that the row should be deleted

**Comment by fakhrihawari** [comment]
Script:
db.user.update({organization_tag:"chad"},{$set:{ organization_name: "Centre for Community Health & Development"}},{multi:true});
db.user.update ({organization_tag:"pac",email:{$regex:/sac.org/g},organization_name:{$ne:"Physicians Across Continents (PAC)"}},{$set:{ organization_name: "Physicians Across Continents (PAC)",organization_type:"International NGO"}},{multi:true});
db.user.update({organization_tag:"qrcs",organization_name:{$ne:"Qatar Red Crescent Society"}},{$set:{ organization_name:"Qatar Red Crescent Society"}},{multi:true});
db.user.update({organization_tag:"sfl"},{$set:{ organization_name:"Shelter For Life International"}},{multi:true});
db.user.update({organization_tag:"unfpa",admin0pcode: {$ne:"COL"},organization_name:{$ne:"United Nations Population Fund"}},{$set:{organization_name:"United Nations Population Fund",organization_type:"United Nations"}},{multi:true});
db.user.update({organization_tag:"sci",organization_name:{$ne:"Save the Children"}},{$set:{ organization_name:"Save the Children"}},{multi:true});

db.user.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria"},{$set:{ organization:"SOS-NG",organization_name:"SOS Children's Villages Nigeria", organization:"sos-ng"}},{multi:true});

db.userhistory.update({organization_tag:"chad"},{$set:{ organization_name: "Centre for Community Health & Development"}},{multi:true});
db.userhistory.update ({organization_tag:"pac",email:{$regex:/sac.org/g},organization_name:{$ne:"Physicians Across Continents (PAC)"}},{$set:{ organization_name: "Physicians Across Continents (PAC)",organization_type:"International NGO"}},{multi:true});
db.userhistory.update({organization_tag:"qrcs",organization_name:{$ne:"Qatar Red Crescent Society"}},{$set:{ organization_name:"Qatar Red Crescent Society"}},{multi:true});
db.userhistory.update({organization_tag:"sfl"},{$set:{ organization_name:"Shelter For Life International"}},{multi:true});
db.userhistory.update({organization_tag:"unfpa",admin0pcode: {$ne:"COL"},organization_name:{$ne:"United Nations Population Fund"}},{$set:{organization_name:"United Nations Population Fund",organization_type:"United Nations"}},{multi:true});
db.userhistory.update({organization_tag:"sci",organization_name:{$ne:"Save the Children"}},{$set:{ organization_name:"Save the Children"}},{multi:true});
db.userhistory.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria"},{$set:{ organization:"SOS-NG",organization_name:"SOS Children's Villages Nigeria", organization:"sos-ng"}},{multi:true});


db.userloginhistory.update({organization_tag:"chad"},{$set:{ organization_name: "Centre for Community Health & Development"}},{multi:true});
db.userloginhistory.update ({organization_tag:"pac",email:{$regex:/sac.org/g},organization_name:{$ne:"Physicians Across Continents (PAC)"}},{$set:{ organization_name: "Physicians Across Continents (PAC)",organization_type:"International NGO"}});
db.userloginhistory.update({organization_tag:"qrcs",organization_name:{$ne:"Qatar Red Crescent Society"}},{$set:{ organization_name:"Qatar Red Crescent Society"}},{multi:true});
db.userloginhistory.update({organization_tag:"sfl"},{$set:{ organization_name:"Shelter For Life International"}},{multi:true});
db.userloginhistory.update({organization_tag:"unfpa",admin0pcode: {$ne:"COL"},organization_name:{$ne:"United Nations Population Fund"}},{$set:{organization_name:"United Nations Population Fund",organization_type:"United Nations"}},{multi:true});
db.userloginhistory.update({organization_tag:"sci",organization_name:{$ne:"Save the Children"}},{$set:{ organization_name:"Save the Children"}},{multi:true});
db.userloginhistory.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria"},{$set:{ organization:"SOS-NG",organization_name:"SOS Children's Villages Nigeria", organization:"sos-ng"}},{multi:true});


db.organization.update({organization_tag:"chad"},{$set:{ organization_name: "Centre for Community Health & Development"}},{multi:true});
db.organization.update ({organization_tag:"pac",admin0pcode: {$ne:"COL"},organization_name:{$ne:"Physicians Across Continents (PAC)"}},{$set:{ organization_name: "Physicians Across Continents (PAC)",organization_type:"International NGO"}},{multi:true});
db.organization.update({organization_tag:"qrcs",organization_name:{$ne:"Qatar Red Crescent Society"}},{$set:{ organization_name:"Qatar Red Crescent Society"}},{multi:true});
db.organization.update({organization_tag:"sfl"},{$set:{ organization_name:"Shelter For Life International"}},{multi:true});
db.organization.update({organization_tag:"unfpa",admin0pcode: {$ne:"COL"},organization_name:{$ne:"United Nations Population Fund"}},{$set:{organization_name:"United Nations Population Fund",organization_type:"United Nations"}},{multi:true});
db.organization.update({organization_tag:"sci",organization_name:{$ne:"Save the Children"}},{$set:{ organization_name:"Save the Children"}},{multi:true});

db.organization.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria"},{$set:{ organization:"SOS-NG",organization_name:"SOS Children's Villages Nigeria", organization:"sos-ng"}},{multi:true});



db.project.update({organization_tag:"chad"},{$set:{ organization_name: "Centre for Community Health & Development"}},{multi:true});
db.project.update({organization_tag:"pac",email:{$regex:/sac.org/g},organization_name:{$ne:"Physicians Across Continents (PAC)"}},{$set:{ organization_name: "Physicians Across Continents (PAC)"}},{multi:true});
db.project.update({organization_tag:"qrcs",organization_name:{$ne:"Qatar Red Crescent Society"}},{$set:{ organization_name:"Qatar Red Crescent Society"}},{multi:true});
db.project.update({organization_tag:"sfl", organization_name:{$ne:"Shelter For Life International"}},{$set:{ organization_name:"Shelter For Life International"}},{multi:true});
db.project.update({organization_tag:"unfpa",admin0pcode: {$ne:"COL"},organization_name:{$ne:"United Nations Population Fund"}},{$set:{organization_name:"United Nations Population Fund"}},{multi:true});
db.project.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria"},{$set:{ organization:"SOS-NG",organization_name:"SOS Children's Villages Nigeria", organization:"sos-ng"}},{multi:true});

db.project.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization_name:"SOS Children's Villages Nigeria",organization:"SOS-NG"}},{multi: true})
db.budgetprogress.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})
db.targetbeneficiaries.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})
db.targetlocation.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})
db.location.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})
db.report.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})
db.beneficiaries.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})
db.stocklocation.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})
db.stockreport.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})
db.stock.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})
db.stockwarehouse.update({organization_tag:"sos", organization: "SOS Children's Villages Nigeria", organization_id:"5fc4e504ae5261116d5fb2ae", organization_id:"5fc4e504ae5261116d5fb2ae"},{$set:{organization_tag:"sos-ng",organization:"SOS-NG"}},{multi: true})

**Comment by fakhrihawari** [comment]
already updated this on DEV
and using this organization_list
https://docs.google.com/spreadsheets/d/1b93jk4Vmlr2Y41Xf2REvqTVZI9AWyc12g11IhlKb9dg/edit#gid=0
