### ISSUE TITLE
RH AF Bugs on Stock Record Page

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#60]
The list of Stock Records is not shown when this page opens.

Open the page by clicking Record Admin > Stock Record.

**Comment by fakhrihawari** [comment]
Already fixed,  there are some missing in tag html due to update from earlier commit

link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/182
updated on DEV and PROD
