### ISSUE TITLE
RH AF Request Delete Button

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#61]
Right now in AF, the delete project button is hidden for common user.

I'm thinking to make it easier to request deleting a project. Well, sometimes the user did make a dummy project for testing the system functionality.

So, the request delete button will show for common users. This button will not be shown to the admin role who can delete the project. 
After the user clicking it, they should choose a reason (or maybe the system can provide a text field instead) for deleting a project.
Then, it will redirect to a confirmation page "Do you want to request deleting this project?"
Finally, the system will send out an email to all org_admin associated with that project and other higher admin role messages below :
Hi! User **X** is requesting to delete project **A** because of **Y**
If you feel this information is correct, kindly delete this project through below link (link to project)

Notes :
Y = reason collected from the user, submitted via the text field or any options shown.

Thoughts?

**Comment by fakhrihawari** [comment]
Demo 

https://user-images.githubusercontent.com/12655589/125407151-cfe67380-e3e3-11eb-8cc2-7deff9e63c19.mp4

**Comment by fakhrihawari** [comment]
Email:

<img width="1371" alt="Screen Shot 2021-07-13 at 14 11 22" src="https://user-images.githubusercontent.com/12655589/125407614-3ec3cc80-e3e4-11eb-98a9-2dbb85cdd00b.png">

**Comment by fakhrihawari** [comment]
Branch:
https://github.com/fakhrihawari/ngm-reportEngine/tree/request-delete-project
https://github.com/fakhrihawari/ngm-reportHub/tree/request-delete-project

**Comment by fakhrihawari** [comment]
link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/196
https://github.com/drfaustusfade/ngm-reportEngine/pull/43

Updated on DEV and PROD
