### ISSUE TITLE
Deactivate User Modal Minor Change

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#62]
<img width="934" alt="Screen Shot 2021-07-14 at 12 51 51" src="https://user-images.githubusercontent.com/28089698/125571545-1f743f10-b59a-4f06-b592-5c9cbc2eac75.png">

Please change the sentences.
Deactivate User

Are you sure you would like to deactivate user xxx?

Yes, Deactivate User!

The button should be red, not green in my opinion.

**Comment by fakhrihawari** [comment]
https://github.com/fakhrihawari/ngm-reportHub/tree/fix-sentry-bug2

**Comment by fakhrihawari** [comment]
<img width="1058" alt="Screen Shot 2021-07-14 at 13 37 10" src="https://user-images.githubusercontent.com/12655589/125574844-5a01c46b-20e8-4973-a23c-44e069e25cff.png">

**Comment by fakhrihawari** [comment]
Already on PR
https://github.com/drfaustusfade/ngm-reportHub/pull/197

Updated on DEV and PROD
