### ISSUE TITLE
Column Update in My Team Page

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#63]
Currently, we have "Update" column on My Team Page
This column should show the last time the user logged in to the system

I found it instead this column shows the last updates did to the user. So, when I try to update several users' roles, the update column content is changed also to the time I update the roles.

Kindly identify the problem and fix this issue.

**Comment by fakhrihawari** [comment]
Already fixed on this PR
https://github.com/drfaustusfade/ngm-reportHub/pull/197

Updated on DEV and PROD

**Comment by rafinkanisa** [comment]
The table was still sorted based on UpdateAt column. I think it would be better to sort it based on last logged in column.

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/200

updated on PROD
