### ISSUE TITLE
Inconsistent Data in last_logged_in and UpdateAt attribute

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#65]
Currently, we have last_logged_in attribute in the database.
I found in the database data of last_logged_in is the same as CreatedAt attribute.  last_logged_in attribute data should at least occur in the same month of the data in UpdateAt.  So, this is precisely another bug in the database.

Kindly identify why this happens and check other users who have the same issue with this user. Perform the cleanup also.

Please share the list and the query to perform the cleaning.

**Comment by fakhrihawari** [comment]
Scripts

db.user.find({last_logged_in: {$lte:ISODate('2021-06-01')}}).forEach(function(u){if(u.last_logged_in !== u.updatedAt){u.last_logged_in = u.updatedAt;db.user.save(u)}; });
db.userhistory.find({last_logged_in: {$lte:ISODate('2021-06-01')}}).forEach(function(u){if(u.last_logged_in !== u.updatedAt){u.last_logged_in = u.updatedAt;db.userhistory.save(u)};});
db.userloginhistory.find({last_logged_in: {$lte:ISODate('2021-06-01')}}).forEach(function(u){if(u.last_logged_in !== u.updatedAt){u.last_logged_in = u.updatedAt;db.userloginhistory.save(u)};});
