### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#66]
There is a user who is from humedica but registered in Aamin as a result of previous bugs.
This user has already request to delete his previous account with Malgaray username.

Please delete this user from the system.
Thanks

**Comment by fakhrihawari** [comment]
Scripts

db.organization.update({admin0pcode:"AF",organization:"humedica",_id:ObjectId('60be124dc841e58020d57d34')},{$set :{organization_type:"International NGO",organization_tag:"humedica",organization_name:"Humedica International Aid"}})
