### ISSUE TITLE
Beneficiary Data Downloaded from My Admin Page downloading different data period

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#67]
So, the IMO from Protection is reaching us because of the issue she just recently knew.
She usually downloading the beneficiary data from My Admin Page. But, in June, the data that she downloaded from My Admin Page is downloading different periods including the 2020 reporting year.

When I check, whenever I changed the date to 30 June 2021, somehow the date periods always jumped to 29 June 2021.
<img width="1679" alt="Screen Shot 2021-07-28 at 15 01 44" src="https://user-images.githubusercontent.com/28089698/127288164-d1d544e1-9ca2-4985-94e2-70a29e8a0894.png">

Kindly identify the issue and please fix this bugs.

**Comment by fakhrihawari** [comment]
Downloading the different data periods: This problem happens because of the missing parameters when sending requests to get file csv.
Link PR that solve this bug
https://github.com/drfaustusfade/ngm-reportHub/pull/202
https://github.com/drfaustusfade/ngm-reportHub/pull/203
