### ISSUE TITLE
Forbid Space Character in Username while Register

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#69]
Currently, when a user registers to RH, they can put any username in it (including space characters). Please forbid the user from doing so. You can also create another rule for the username input if you see fit.

Any other input text that needs to be adjusted is open for any changes. Kindly inform it here.

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/drfaustusfade/ngm-reportHub/pull/214
