### ISSUE TITLE
Add New Organizations to RH

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#7]
Add below organization to the ReportHub :

Technical Education and Skill Training Organization
Watan's Social and Technical Services Association
SANAYEE DEVELOPMENT ORGANIZATION
Afghanistan National Reconstruction Coordination

Currently, we haven't had any reply of the correct abbreviation. Writing this here just as a reminder for us to add those organizations.

**Comment by fakhrihawari** [comment]
Updated on PROD and DEV
