### ISSUE TITLE
RH NG - Enabled SADD inputs for WASH activities in Nigeria

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#70]
The IM from Nigeria was requesting to enable all of the SADD inputs in the activity plan once they start a new period.

Probably, in the coming weeks, we'll have to update it.

**Comment by rafinkanisa** [comment]
will wait until their old project is over.

**Comment by rafinkanisa** [comment]
Kindly proceed to update the SADD group to be visible

As shown below, the SADD & HH are automatically being calculated in the monthly report
https://user-images.githubusercontent.com/28089698/144587866-67d5c638-6f01-4eee-bc26-f99ac99d1c30.mov

Keep it automatically counted but make it disabled for users to edit by themselves (not hide the SADD & HH) in Report.
So, make ALL of the HH & SADD be available in the Project Plan.
The users should be able to input the numbers by themselves in the Target Population

**Comment by rafinkanisa** [comment]
I have checked in DEV but the HH could be edited. I think this shouldn't be happened as when I input the Kit numbers, it automatically calculate the number of HH. See below video

https://user-images.githubusercontent.com/28089698/145337660-f674de07-6693-4f3a-a1e2-0f216ac64afb.mov

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/iMMAP/ngm-reportHub/pull/85
