### ISSUE TITLE
Create HTML Email Template

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#71]
Create an HTML Email template that inline with the ReportHub design. Change all of the associated notifications that were sent by email with the new email template.

Make sure it is responsive enough so, the email won't distort in mobile. Thanks.

**Comment by fakhrihawari** [comment]
<img width="636" alt="user-pending-template-email" src="https://user-images.githubusercontent.com/12655589/128982806-4892ddc0-c9e7-4b4c-aa50-7554734acffb.png">
<img width="614" alt="password-reset-template-email" src="https://user-images.githubusercontent.com/12655589/128982814-cda2e1ff-f354-4ad8-a35a-1ea56315050b.png">
<img width="610" alt="user-activated--template-email" src="https://user-images.githubusercontent.com/12655589/128982815-9bd56623-6f88-4938-a770-affd1d680e3e.png">
<img width="611" alt="user-deactivated-notification-template-email" src="https://user-images.githubusercontent.com/12655589/128982817-e428b8a4-4d91-430d-81f5-5b8c54347a4f.png">
<img width="603" alt="new-user-template-email" src="https://user-images.githubusercontent.com/12655589/128982822-2e78cbaa-c270-4072-aac0-dc9903676ecd.png">
<img width="630" alt="delete-Project_new_template_email" src="https://user-images.githubusercontent.com/12655589/128982826-f5cbd6a6-03e2-454c-8909-9969b7ad0a5c.png">

**Comment by rafinkanisa** [comment]
Put one screenshot of the general design here

**Comment by fakhrihawari** [comment]
https://github.com/drfaustusfade/ngm-reportHub/pull/249
