### ISSUE TITLE
Change the Writings in Email Notification for New User

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#72]
Currently, the notification which was sent by email every time a new user signs up is writing all of the admin names.
Kindly change it so the email only mentions one admin name in each of the emails that were sent.
So, the final structure will be :

Hi admin_name,

A new user has registered to your organization (organization_name). The details are provided below.

**Country** : country_name
**Sector** : sector_name
**Username** : username
**Name** : name
**Position** : position_name
**Phone** : phone_numb
**Email** : email_address

If you do not recognize this user as a member of your organization, please disable them from your organization from the User Profile Page.

Alternatively, please feel free to respond to this email to inform the ReportHub team.

ReportHub

Notes:
admin_name should only consist of one admin only.
If you would like to keep the "to" email address be visible to all admin, we can just change admin_name to "Admin of organization_name Organization"

**Comment by fakhrihawari** [comment]
<img width="614" alt="Screen Shot 2021-08-13 at 10 47 46" src="https://user-images.githubusercontent.com/12655589/129302304-40d98fcc-3a82-4048-8a2a-594f0973d66a.png">

**Comment by rafinkanisa** [comment]
Put comma at the end of the name "Hi ....,"
Check the words "If you do not..." to match below screenshots and used fonts-size : 16px (same as above)
User Profile Page as link
Bold font in "do not recognize" and "disable"
For the "Alternatively, ...." use font-size : 13px; color : #a7a1a1; center-align;

<img width="1422" alt="Screen Shot 2021-08-18 at 11 46 07" src="https://user-images.githubusercontent.com/28089698/129838479-59cc20da-0e0e-4525-89d5-1d0e6d51f380.png">


Kindly give me your thoughts

**Comment by fakhrihawari** [comment]
<img width="605" alt="Screen Shot 2021-08-19 at 08 55 15" src="https://user-images.githubusercontent.com/12655589/129995244-90e720da-11b9-4f08-a6f6-07e4d82851d8.png">

**Comment by rafinkanisa** [comment]
"......this user as a member of org_abbr........"
User Profile Page as link

**Comment by fakhrihawari** [comment]
<img width="604" alt="Screen Shot 2021-08-19 at 10 51 14" src="https://user-images.githubusercontent.com/12655589/130004827-1f3d32a6-8b7f-4a53-8bfd-ac5925f91b7c.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After revision
<img width="601" alt="Screen Shot 2021-08-30 at 10 38 53" src="https://user-images.githubusercontent.com/12655589/131281963-e2cb31eb-8e35-47b1-b772-f8473d847bd6.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
