### ISSUE TITLE
Change the Writings in Email Notification for New Pending User

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#73]
Currently, the notification which was sent by email every time a new user signs up is writing all of the admin names.
Kindly change it so the email only mentions one admin name in each of the emails that were sent.
So, the final structure will be :

Hi admin_name,

A new user who has registered to your organization (organization_name) is **WAITING** to be **ACTIVATED**. The details are provided below.

**Country** : country_name
**Sector** : sector_name
**Username** : username
**Name** : name
**Position** : position_name
**Phone** : phone_numb
**Email** : email_address

If you recognize this user as a member of your organization, please **ENABLE** them from the User Profile Page.

Alternatively, please feel free to respond to this email to inform the ReportHub team.

ReportHub

Notes:
admin_name should only consist of one admin only.

If you would like to keep the "to" email address be visible to all admin, we can just change admin_name to "Admin of organization_name Organization"

**Comment by fakhrihawari** [comment]
<img width="604" alt="Screen Shot 2021-08-13 at 11 26 27" src="https://user-images.githubusercontent.com/12655589/129304780-05eeab76-e26e-4d41-bd75-7a403ba398c2.png">

**Comment by rafinkanisa** [comment]
Give dots after "... provided below."
Remove <.br> after bullet points.
Bullet point and "If you recognize..." using same font size: 16px
"... as a member of org_abbr, ...."
Remove words user (check screenshot below)
For the "Alternatively, ...." use font-size : 13px; color : #a7a1a1; center-align;


<img width="1422" alt="Screen Shot 2021-08-18 at 12 10 59" src="https://user-images.githubusercontent.com/28089698/129840788-801f472d-2a1f-4861-952d-4ef124d1457f.png">

**Comment by fakhrihawari** [comment]
<img width="608" alt="Screen Shot 2021-08-19 at 09 17 22" src="https://user-images.githubusercontent.com/12655589/129997035-1ecb6a1f-e091-4426-bd10-7d422111e4a1.png">

**Comment by rafinkanisa** [comment]
Remove words "user" not link (check screenshot) ---> "..... from the User Profile Page or ....."

**Comment by fakhrihawari** [comment]
<img width="606" alt="Screen Shot 2021-08-19 at 10 12 39" src="https://user-images.githubusercontent.com/12655589/130001745-892f2de3-f69c-4821-8c7a-2d718091a3dd.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
![Uploading Screen Shot 2021-08-19 at 10.12.39.png…]()

**Comment by fakhrihawari** [comment]
<img width="606" alt="Screen Shot 2021-08-19 at 10 12 39" src="https://user-images.githubusercontent.com/12655589/130001928-962b012f-8c81-4573-950b-010689fdbe5f.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After revision
<img width="600" alt="Screen Shot 2021-08-30 at 10 50 49" src="https://user-images.githubusercontent.com/12655589/131282674-ebc1c71a-99f0-4443-94f3-7214e46a3995.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
