### ISSUE TITLE
Change the Writings in Email Notification for Pending Report

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#74]
So, the final structure will be :

Hi name,
There are reports being **NOT SUBMITTED**!

Follow the links below to complete and submit your **PENDING** Monthly Activity Reports.
**Country | Cluster | Project Title | Link** -- table --
country_name | cluster_name | project_title | button ( written in : month Monthly Activity Report)

Apply this format to ALL country except AF.

**Comment by fakhrihawari** [comment]
<img width="607" alt="Screen Shot 2021-08-16 at 10 44 52" src="https://user-images.githubusercontent.com/12655589/129508804-b1ba79c1-652f-4f29-a069-ed71cf96b5e3.png">

**Comment by rafinkanisa** [comment]
Kindly add the month and year also to the table

**Comment by fakhrihawari** [comment]
<img width="608" alt="Screen Shot 2021-08-18 at 16 27 40" src="https://user-images.githubusercontent.com/12655589/129874531-37e2f96d-2751-4341-aaf3-ee7a02e06f93.png">

alternative

<img width="612" alt="Screen Shot 2021-08-18 at 16 30 07" src="https://user-images.githubusercontent.com/12655589/129874578-169b96ef-b9d1-49d1-8378-3e5b76692346.png">

**Comment by fakhrihawari** [comment]
<img width="606" alt="Screen Shot 2021-08-18 at 16 55 18" src="https://user-images.githubusercontent.com/12655589/129878411-1e450df5-2cfb-4bf0-962f-b77ebee1e06e.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After revision
<img width="606" alt="Screen Shot 2021-08-30 at 13 33 08" src="https://user-images.githubusercontent.com/12655589/131295560-f0544000-2ea4-45c4-ab88-87edca5722fd.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

unbold "BEEN"

**Comment by fakhrihawari** [comment]
<img width="606" alt="Screen Shot 2021-09-14 at 14 15 59" src="https://user-images.githubusercontent.com/12655589/133212537-7ee78e85-6d31-4be6-a1d7-efebfac8f2e7.png">

<img width="600" alt="Screen Shot 2021-09-14 at 14 15 09" src="https://user-images.githubusercontent.com/12655589/133212425-acec5e8f-5584-4ea4-a354-4d74977a2789.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
