### ISSUE TITLE
Change the Writings in Email Notification for Password Reset

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#75]
So, the final structure will be :

Hi name,

You are receiving this email because we received a password reset request for your ReportHub Account. No changes have been made to your account yet.

Click one of the links below to reset your password.

**Country | Sector | Username | Link** -- table --
country_name | sector_name | username | button (write : Reset Password)

If you did not request a password reset, you can safely ignore this email. Only a person with access to your email can reset your password account. -- text center and lighter font colour --

Well, it's hard to write it out here. Basically, it should be formatted as table and the warning message is center align with lighter font colour (possibly grey)

**Comment by fakhrihawari** [comment]
<img width="609" alt="Screen Shot 2021-08-13 at 13 53 21" src="https://user-images.githubusercontent.com/12655589/129316820-3f9eb22c-02d6-47ec-a89f-9a83c671193d.png">

**Comment by rafinkanisa** [comment]
After viewing your screenshot, I think it would be better to make the "password reset" bold.
Sentences for "No changes...." start below. And, "Click one of ...." is put in the same row as previous sentence. Please see below to have a more clear understanding.

<img width="603" alt="Screen Shot 2021-08-13 at 14 43 04" src="https://user-images.githubusercontent.com/28089698/129323322-3292c8f8-2c3d-4aea-af1d-14d9d8e08a38.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After Revision

<img width="602" alt="Screen Shot 2021-08-30 at 10 13 49" src="https://user-images.githubusercontent.com/12655589/131280037-70d9e92d-2b7a-4297-a5e5-beb362e40520.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
