### ISSUE TITLE
Change the Writings in Email Notification for Delete Request

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#76]
So, the final structure will be :

Hi admin_name,

User requester_username ( requester_name ) is requesting to delete a project.

Kindly find the details below.
**Country** : country_name
**Project Title** : project_title
**Reason** : reason

If you feel this information is correct, kindly delete this project through this link

WARNING!

Deleting a project will **permanently removing** all the project data including the submitted monthly report. The ReportHub Team **CANNOT UNDO** this action.

ReportHub

**Comment by fakhrihawari** [comment]
<img width="627" alt="Screen Shot 2021-08-13 at 10 56 33" src="https://user-images.githubusercontent.com/12655589/129302868-bc0e458b-5943-4b99-953b-09ab77547a21.png">

**Comment by fakhrihawari** [comment]
<img width="605" alt="Screen Shot 2021-08-13 at 11 07 56" src="https://user-images.githubusercontent.com/12655589/129303592-c883c37d-5b3c-4230-b108-ebfb57d6b383.png">

**Comment by rafinkanisa** [comment]
After reviewing, I think it would be better to change the warning like the below picture.
Please note that I use this format:
Warning font-size : 15px; margin-top: 40px;
For the description below I use font-size : 13px; color : #a7a1a1; disable font-weight;
for the bold text I use this color : #585353

left-align:
<img width="541" alt="Screen Shot 2021-08-13 at 15 17 42" src="https://user-images.githubusercontent.com/28089698/129329324-851d84e4-67d7-452e-a48b-6ba9357475be.png">

alternative center text :
<img width="542" alt="Screen Shot 2021-08-13 at 15 16 51" src="https://user-images.githubusercontent.com/28089698/129329388-8456c582-436a-450a-a6ec-f0b676193336.png">

**Comment by fakhrihawari** [comment]
![Uploading Screen Shot 2021-08-18 at 12.46.20.png…]()

**Comment by fakhrihawari** [comment]
<img width="647" alt="Screen Shot 2021-08-18 at 12 46 20" src="https://user-images.githubusercontent.com/12655589/129844116-cb5b40c9-8b27-43cb-8ea3-91bba5cc4540.png">

**Comment by rafinkanisa** [comment]
Put "The ReportHub Team...." be in the same row as previous. don't use <.br> (see screenshots above)

**Comment by fakhrihawari** [comment]
<img width="608" alt="Screen Shot 2021-08-18 at 12 56 27" src="https://user-images.githubusercontent.com/12655589/129845310-97426684-51ef-4180-b766-17de8f789313.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After Revision

<img width="602" alt="Screen Shot 2021-08-30 at 10 30 03" src="https://user-images.githubusercontent.com/12655589/131281115-b50e1d54-a0c3-4424-9cd1-204f774f4e4a.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

Please add the focal point information also

**Comment by fakhrihawari** [comment]
<img width="610" alt="Screen Shot 2021-09-14 at 13 22 58" src="https://user-images.githubusercontent.com/12655589/133205717-b9440eeb-97b6-4405-b70d-3246c682abc1.png">

**Comment by rafinkanisa** [comment]
Apply one of the below screenshots please (which ever you like)

<img width="604" alt="Screen Shot 2021-09-14 at 14 55 06" src="https://user-images.githubusercontent.com/28089698/133219624-436bace3-f3f9-4a75-a4a1-881854dc9802.png">

<img width="604" alt="Screen Shot 2021-09-14 at 14 57 06" src="https://user-images.githubusercontent.com/28089698/133219661-36915184-9359-4697-a83a-f57f9113915e.png">

**Comment by fakhrihawari** [comment]
<img width="606" alt="Screen Shot 2021-09-14 at 15 58 32" src="https://user-images.githubusercontent.com/12655589/133228091-f7e107e2-7541-45df-b812-1231b599c265.png">

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
