### ISSUE TITLE
Change the Writings in Email Notification for Pending Report in AF

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#77]
So, the final structure will be :

Hi name,
The reporting period for **month year** is **PENDING**!

Follow the links below to complete and submit your **PENDING** Monthly Activity Reports.
**Country | Cluster | Project Title | Link** -- table --
country_name | cluster_name | project_title | button ( written in : month Monthly Activity Report)

Apply this only in Afghanistan

**Comment by fakhrihawari** [comment]
![Uploading Screen Shot 2021-08-16 at 10.13.20.png…]()

**Comment by fakhrihawari** [comment]
<img width="605" alt="Screen Shot 2021-08-16 at 10 13 20" src="https://user-images.githubusercontent.com/12655589/129506725-79ed52e4-12b5-42fa-8789-08e3e708a0f1.png">

**Comment by rafinkanisa** [comment]
Kindly add the month and year also to the table

**Comment by rafinkanisa** [comment]
Kindly delete the comma in "July, 2021"

**Comment by fakhrihawari** [comment]
<img width="613" alt="Screen Shot 2021-08-18 at 15 59 10" src="https://user-images.githubusercontent.com/12655589/129869791-eac0f5d9-fe4d-461a-989b-a794aa31cd3f.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After revision
<img width="604" alt="Screen Shot 2021-08-30 at 13 12 07" src="https://user-images.githubusercontent.com/12655589/131293469-f4e6ae07-3be4-46a8-970e-6fa72854b986.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

But keep the "Monthly Activity" in the button as before

**Comment by fakhrihawari** [comment]
<img width="603" alt="Screen Shot 2021-09-14 at 14 05 30" src="https://user-images.githubusercontent.com/12655589/133211175-c50ede34-6f67-4022-9f47-45e54906c0b3.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
