### ISSUE TITLE
Change the Writings in Email Notification for DUE

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#78]
So, the final structure will be :

Hi name,
The reporting period for **month year** is **DUE TODAY**!

Follow the links below to complete and submit your **PENDING** Monthly Activity Reports.
**Country | Cluster | Project Title | Link** -- table --
country_name | cluster_name | project_title | button ( written in : month Monthly Activity Report)

**Comment by fakhrihawari** [comment]
<img width="661" alt="Screen Shot 2021-08-13 at 16 45 34" src="https://user-images.githubusercontent.com/12655589/129338622-d11f8cca-eb74-4ef9-9547-7aacc316d88a.png">

**Comment by fakhrihawari** [comment]
<img width="604" alt="Screen Shot 2021-08-16 at 09 43 44" src="https://user-images.githubusercontent.com/12655589/129504611-4d7996bb-7559-4bd5-a768-3095e0b2e183.png">

**Comment by rafinkanisa** [comment]
Kindly delete the comma in "July, 2021"

**Comment by fakhrihawari** [comment]
<img width="605" alt="Screen Shot 2021-08-18 at 15 53 20" src="https://user-images.githubusercontent.com/12655589/129868835-328dbe44-a957-432b-b176-83f1346d3602.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After revision
<img width="601" alt="Screen Shot 2021-08-30 at 13 04 57" src="https://user-images.githubusercontent.com/12655589/131292876-9b529c1d-af1e-43a1-abb9-f0ddbd750981.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

but keep the "Monthly Activity" in the button as before

**Comment by fakhrihawari** [comment]
<img width="600" alt="Screen Shot 2021-09-14 at 13 47 39" src="https://user-images.githubusercontent.com/12655589/133208906-4eccf420-1750-486d-9705-4c253b751dc1.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
