### ISSUE TITLE
Change the Writings in Email Notification for SOON

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#79]
So, the final structure will be :

Hi name,
The reporting period for **month year** is **DUE SOON**!

Follow the links below to complete and submit your **PENDING** Monthly Activity Reports.
**Country | Cluster | Project Title | Link** -- table --
country_name | cluster_name | project_title | button ( written in : month Monthly Activity Report)

**Comment by fakhrihawari** [comment]
<img width="609" alt="Screen Shot 2021-08-13 at 16 49 36" src="https://user-images.githubusercontent.com/12655589/129339115-93c53cb2-7734-450d-95f6-2864224a99eb.png">

**Comment by fakhrihawari** [comment]
<img width="612" alt="Screen Shot 2021-08-16 at 09 38 02" src="https://user-images.githubusercontent.com/12655589/129504210-774a6210-2aa7-4ffa-874d-6d9d285a9238.png">

**Comment by rafinkanisa** [comment]
Kindly delete the comma in "July, 2021"

**Comment by fakhrihawari** [comment]
![Uploading Screen Shot 2021-08-18 at 15.48.52.png…]()

**Comment by fakhrihawari** [comment]
<img width="604" alt="Screen Shot 2021-08-18 at 15 48 52" src="https://user-images.githubusercontent.com/12655589/129868152-0535f4f8-bab5-4477-b93f-598805e4baed.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After revision

<img width="600" alt="Screen Shot 2021-08-30 at 13 16 39" src="https://user-images.githubusercontent.com/12655589/131293873-5c4379ad-cbaf-4ec7-be75-622c3bdd779f.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

but keep the "Monthly Activity" in the button as before

**Comment by fakhrihawari** [comment]
<img width="607" alt="Screen Shot 2021-09-14 at 13 59 04" src="https://user-images.githubusercontent.com/12655589/133210424-181732c1-d280-45fe-8ed3-ca42896bd10d.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
