### ISSUE TITLE
Label for beneficiaries w/ disabilities

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#8]
There are partners who put the total number of SADD even though they have selected the category Persons w/ disabilities. Make the label for beneficiaries w/ disabilities more clear. We can just use visible tag to solve this issue.

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/drfaustusfade/ngm-reportHub/pull/140
Updated on PROD and DEV
