### ISSUE TITLE
Change the Writings in Email Notification for OPEN

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#80]
So, the final structure will be :

Hi name,
The Monthly Activity reporting period for **month year (capitalized)** is now **OPEN**! 

Follow the links below to complete the report.
**Country | Cluster | Project Title | Link** -- table --
country_name | cluster_name | project_title | button ( written in : month Activity Report)

**Comment by fakhrihawari** [comment]
<img width="620" alt="Screen Shot 2021-08-16 at 09 10 27" src="https://user-images.githubusercontent.com/12655589/129502308-f6a8c8cd-2d1e-40d8-93ae-2f1aa777fb09.png">

**Comment by fakhrihawari** [comment]
![Uploading Screen Shot 2021-08-16 at 09.25.20.png…]()

**Comment by fakhrihawari** [comment]
<img width="615" alt="Screen Shot 2021-08-16 at 09 25 20" src="https://user-images.githubusercontent.com/12655589/129503283-08d88e06-cc02-451d-b6af-a036436a194a.png">

**Comment by rafinkanisa** [comment]
Kindly delete the comma in "August, 2021"

**Comment by fakhrihawari** [comment]
<img width="607" alt="Screen Shot 2021-08-19 at 08 32 26" src="https://user-images.githubusercontent.com/12655589/129993510-f009cd10-9a81-4ecf-8826-2698408d3ebc.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After revision
<img width="602" alt="Screen Shot 2021-08-30 at 13 24 54" src="https://user-images.githubusercontent.com/12655589/131294933-a83b9af6-c592-44f7-b8e5-886ea3b0f4f3.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

But keep the "Monthly Activity" in the button as before
use "report" instead "reporting period"

**Comment by fakhrihawari** [comment]
<img width="604" alt="Screen Shot 2021-09-14 at 13 55 06" src="https://user-images.githubusercontent.com/12655589/133209871-be649e53-5fdb-4a6e-844e-755e02494d52.png">

**Comment by rafinkanisa** [comment]
The monthly activity report for September 2021 is now OPEN.

use "report" instead "reporting period"

**Comment by fakhrihawari** [comment]
<img width="607" alt="Screen Shot 2021-09-14 at 16 07 28" src="https://user-images.githubusercontent.com/12655589/133229566-cb568d49-2d2c-490a-bc94-92721111c428.png">

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
