### ISSUE TITLE
Change the Writings in Email Notification for New Organization

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#81]
Currently, the notification which was sent by email every time a new user signs up is writing all of the admin names.
Kindly change it so the email only mentions one admin name in each of the emails that were sent.
So, the final structure will be :

Hi admin_name,

You are receiving this notification because you are administered either as CLUSTER or  COUNTRY_ADMIN role.
We just notice the organization **organization_name** has just created an account in ReportHub. The details are provided below.

**Country** : country_name
**Sector** : sector_name
**Username** : username
**Name** : name
**Position** : position_name
**Phone** : phone_numb
**Email** : email_address

If you do not recognize this user as a member of **organization_name**, please disable them from organization_name organization from the User Profile Page.

Alternatively, please feel free to respond to this email to inform the ReportHub Team.

ReportHub

Notes:
admin_name should only consist of one admin only.
If you would like to keep the "to" email address be visible to all admin, we can just change admin_name to "Admin of organization_name Organization" --- depends on the answer of below question

Kindly give me the details, when a new organization just registered to the system, who will get the notification? Is it only iMMAP admin in that country or ALL admin that has role country?
So, I could adjust the writings accordingly.

Thanks

**Comment by fakhrihawari** [comment]
<img width="604" alt="Screen Shot 2021-08-13 at 16 16 27" src="https://user-images.githubusercontent.com/12655589/129334847-3474484b-9d98-454b-a32c-3f96e9e85c10.png">

**Comment by rafinkanisa** [comment]
After reviewing, I think, it would be better to be like below screenshots
Remove <.br> after <.ul>
"If you do not recognize..." using same font size: 15px
"... please disable them from org_abbr organization ...."
Bold font in "do not recognize" and "disable"
User Profile Page as link
Remove dot after Profile Page
For the "Alternatively, ...." use font-size : 13px; color : #a7a1a1; center-align;
Put "You are receiving ...." below this sentence.

<img width="481" alt="Screen Shot 2021-08-18 at 12 42 31" src="https://user-images.githubusercontent.com/28089698/129843721-9144f0e9-808d-4cfd-b07b-13e0d52b3ce6.png">

**Comment by fakhrihawari** [comment]
<img width="609" alt="Screen Shot 2021-08-19 at 09 06 29" src="https://user-images.githubusercontent.com/12655589/129996138-7b4a697e-a235-4ad6-9816-5fa3d764f9e7.png">

**Comment by rafinkanisa** [comment]
Remove <.br> after <.ul>
"... please disable them from org_abbr organization ...."
User Profile Page as link
Remove dot after Profile Page

Did you change the subject? Because I couldn't see subject "ReportHub - New Organization iMMAP!"

**Comment by fakhrihawari** [comment]
<img width="610" alt="Screen Shot 2021-08-19 at 10 47 37" src="https://user-images.githubusercontent.com/12655589/130004586-b6c91ced-12b2-4b3a-8c7b-9301f07d48cc.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After Revision
<img width="601" alt="Screen Shot 2021-08-30 at 11 12 19" src="https://user-images.githubusercontent.com/12655589/131284307-76e7acce-cb72-45b5-94c6-ef7ee16efac1.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

remove <.br> after <.ul>

**Comment by fakhrihawari** [comment]
<img width="602" alt="Screen Shot 2021-09-14 at 13 37 09" src="https://user-images.githubusercontent.com/12655589/133207552-e9b57c62-044f-4961-821a-713149598dfa.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
