### ISSUE TITLE
Change the Writings in Email Notification for Activate Account

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#82]
So, the final structure will be :

Hi name,

Welcome and Thank you for registering at ReportHub!
Your account with details below has now been **ACTIVATED**. You can edit your personal details on the (Profile Page - link).

**Country** : country_name
**Sector** : sector_name
**Organization** : organization_name
**Username** : username
**Name** : name
**Position** : position_name
**Phone** : phone_numb
**Email** : email_address

You can login by using your username and password through the following link (https://reporthub.org/desk/#/cluster/login) or click the button below.

ReportHub

**Comment by fakhrihawari** [comment]
<img width="603" alt="Screen Shot 2021-08-13 at 15 39 30" src="https://user-images.githubusercontent.com/12655589/129329779-22eee6f1-836c-4a8c-886d-f251feea0d42.png">

**Comment by rafinkanisa** [comment]
Profile Page is link.  please remove the ()
Remove <.br> after <.ul>
Change Go to Login --> Login to ReportHub
In my opinion, "You can login ....." be in the same font-size: 15px;

What do you think?

See picture below:
<img width="542" alt="Screen Shot 2021-08-13 at 16 04 33" src="https://user-images.githubusercontent.com/28089698/129333277-d2583ef0-9bb9-4fc8-9021-f45d3798dfc4.png">

**Comment by fakhrihawari** [comment]
<img width="606" alt="Screen Shot 2021-08-19 at 09 56 52" src="https://user-images.githubusercontent.com/12655589/130000416-4eb6dd93-28a4-4c4d-8857-2bd859fcc04b.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After Revision
<img width="605" alt="Screen Shot 2021-08-30 at 10 56 59" src="https://user-images.githubusercontent.com/12655589/131283354-a37c5dc8-4e77-45d7-ac58-c8109af6f978.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
