### ISSUE TITLE
Give a Highlight for user that needs to be activated in the table

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#83]
It's hard as an admin to differentiate users who just registered and are in PENDING state waiting for ACTIVATED.
Because it is mixed with the account who has already deactivated.

Currently, I still doesn't have an idea how to make it easier. Just dropping the issue here and let's see what could be done.

**Comment by fakhrihawari** [comment]
how we put some tag like this?
<img width="1274" alt="Screen Shot 2021-08-16 at 14 26 45" src="https://user-images.githubusercontent.com/12655589/129526703-c5dbf5c9-ff6a-4ba1-8f4f-8610a21a0c1a.png">

**Comment by rafinkanisa** [comment]
yeeah.... that's a good idea
so, the user can differentiate better which one is waiting for activation.

what about giving a tooltip also? when the user hovers the pending tag, a tooltip will show describing that "Waiting for Activation. Go to Profile Page to Activate this New User"

**Comment by fakhrihawari** [comment]
<img width="1339" alt="Screen Shot 2021-08-18 at 08 48 16" src="https://user-images.githubusercontent.com/12655589/129823654-48f50b2f-dfbe-4246-ba4b-e34b72c590b6.png">

**Comment by rafinkanisa** [comment]
Can you put in dev so I could check?

**Comment by fakhrihawari** [comment]
Link PR:

https://github.com/drfaustusfade/ngm-reportHub/pull/217
