### ISSUE TITLE
Change the Writings in Email Notification for EDIT Report

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#84]
Currently, the notification which was sent by email every time a report edited is writing all of the admin names.
Kindly change it so the email only mentions one admin name in each of the emails that were sent.
The subject needs to be corrected also to:
ReportHub Notifications: Edit of month, year Report by org_abbr

So, the final structure will be :

Hi admin_name,

Please note that org_abbr (org_name) have updated the following report for month, year. The details are provided below.
**Country** : country_name
**Project Title** : project_title

To view the edits by org_abbr for month, year, follow the link here or click the button below

You are receiving this notification because you are administered as a CLUSTER admin role. --lighter font-colour possibly grey with smaller font-size and center align--

ReportHub

Notes:
admin_name should only consist of one admin only.
If you would like to keep the "to" email address be visible to all admin, we can just change admin_name to "Admin of Cluster cluster_name"

**Comment by rafinkanisa** [comment]
Don't forget to change the subject also

<img width="1391" alt="Screen Shot 2021-08-18 at 09 39 01" src="https://user-images.githubusercontent.com/28089698/129828228-36243290-abd8-4ed0-b9c8-8a277eebfabf.png">

**Comment by fakhrihawari** [comment]
<img width="622" alt="Screen Shot 2021-08-18 at 10 17 02" src="https://user-images.githubusercontent.com/12655589/129831369-896e4e70-a4d5-461e-aaf3-bda0c3afee24.png">

**Comment by fakhrihawari** [comment]
<img width="661" alt="Screen Shot 2021-08-18 at 10 42 38" src="https://user-images.githubusercontent.com/12655589/129833497-a2195ae4-50f4-43c2-b28d-f65c297f9e40.png">

**Comment by rafinkanisa** [comment]
well done!

**Comment by fakhrihawari** [comment]
After revision

<img width="605" alt="Screen Shot 2021-08-30 at 12 53 20" src="https://user-images.githubusercontent.com/12655589/131291811-f8b6bd01-4f60-44d0-8985-59c2d3f95a2d.png">

**Comment by rafinkanisa** [comment]
You have received this notification because you are registered as a cluster admin.

**Comment by fakhrihawari** [comment]
<img width="607" alt="Screen Shot 2021-09-14 at 14 27 47" src="https://user-images.githubusercontent.com/12655589/133214207-99a95b5a-eed4-4168-91db-712092a4ccf4.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
PR 
https://github.com/drfaustusfade/ngm-reportHub/pull/249
