### ISSUE TITLE
Change the Writings in Email Notification for DEACTIVATE User

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#85]
So, the final structure will be :

Hi name,

The following ReportHub users have been inactive for more than 7 months and have been **DEACTIVATED**:

**Country | Sector | Organization | Username ** -- table --
country_name | sector_name | org_abbr | username 

To re-activate your ReportHub Account, please contact your organization or cluster admin.
Alternatively, please feel free to respond to this email to inform the ReportHub Team.

**Comment by fakhrihawari** [comment]
<img width="631" alt="Screen Shot 2021-08-18 at 12 25 36" src="https://user-images.githubusercontent.com/12655589/129842080-4d993fad-33bf-4233-8b2a-ee5b5e176361.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by rafinkanisa** [comment]
Kindly disaggregate 2 different usernames into 2 rows

**Comment by fakhrihawari** [comment]
After revision
<img width="615" alt="Screen Shot 2021-08-30 at 14 40 17" src="https://user-images.githubusercontent.com/12655589/131303760-ba307f39-b6f9-4844-8b92-21c02e4a189a.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
