### ISSUE TITLE
Change the Writings in Email Notification for INACTIVE User

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#86]
So, the final structure will be :

Hi name,

The following ReportHub users have been **INACTIVE** for more than 7 months :

**Country | Sector | Organization | Username | Link** -- table --
country_name | sector_name | org_abbr | username  | button (write : Go to Profile )

Please login to ReportHub to avoid being **DEACTIVATED**. You can review the user profiles using the above links.

**Comment by fakhrihawari** [comment]
<img width="675" alt="Screen Shot 2021-08-18 at 11 39 59" src="https://user-images.githubusercontent.com/12655589/129838017-4a87bf51-bbca-4a26-9faf-8a05c69ec7d6.png">

**Comment by fakhrihawari** [comment]
![Uploading Screen Shot 2021-08-18 at 11.45.51.png…]()

**Comment by fakhrihawari** [comment]
<img width="694" alt="Screen Shot 2021-08-18 at 11 45 51" src="https://user-images.githubusercontent.com/12655589/129838478-68ca1504-5be9-4d37-90f2-0a792519512e.png">

**Comment by rafinkanisa** [comment]
I think we have to add "each", so the sentences :
"Please login to each ReportHub Account....."

**Comment by fakhrihawari** [comment]
<img width="623" alt="Screen Shot 2021-08-19 at 09 45 27" src="https://user-images.githubusercontent.com/12655589/129999331-124bb103-08ea-4505-aaab-0d96ceef2630.png">

**Comment by rafinkanisa** [comment]
Well done!

**Comment by fakhrihawari** [comment]
After revision

<img width="614" alt="Screen Shot 2021-08-30 at 14 30 46" src="https://user-images.githubusercontent.com/12655589/131302604-51983b75-3248-42bf-a609-c3d353d55d67.png">

**Comment by rafinkanisa** [comment]
passed writing suggestion by daniel

**Comment by fakhrihawari** [comment]
https://github.com/drfaustusfade/ngm-reportHub/pull/249
