### ISSUE TITLE
Add Focal Point Information to Delete Request Email

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#88]
After reviewing, I think, we need to add the Focal Point of the project information to the email sent to the admin.

So, we could know who the requester is and the focal point of the project.
If the requester is different from the focal point, then, the admin should confirm to the focal point first.

**Comment by rafinkanisa** [comment]
Related to https://github.com/rafinkanisa/ngm-reportDesk/issues/76

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/249
