### ISSUE TITLE
Create Explanation in Activity Plan - Partners Section

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#90]
Put information about Partners type in the Activity Plan because this is something that was frequently asked by partners.

Project Partners : If this Activity Plan collaborates with other partners, tick one of the partner type (Implementing/Programme) and specify the organization from the dropdown list. Leave it blank if you're working on your own.

Implementing Partner : Partner who take the project and implement in the field.
Programme Partner :  Partner who leading and administering the project.

It should be something like this
<img width="295" alt="Screen Shot 2021-09-06 at 16 11 45" src="https://user-images.githubusercontent.com/28089698/132191969-cd8ee5ed-6f7f-41a6-8af4-004f3a512b01.png">

Put a question mark with circle and if it's clicked, the explanation will be visible

If you have a better idea, then please let me know.

**Comment by fakhrihawari** [comment]
<img width="901" alt="Screen Shot 2021-09-07 at 14 54 33" src="https://user-images.githubusercontent.com/12655589/132306560-bbeca4f6-401b-4e37-87f9-6de5f640302a.png">

**Comment by rafinkanisa** [comment]
That's good. Don't forget to put the explanation also in the Project Partner

How does it look like if the text is left align?

**Comment by fakhrihawari** [comment]
<img width="514" alt="Screen Shot 2021-09-13 at 10 07 42" src="https://user-images.githubusercontent.com/12655589/133018097-a48f434d-3aac-452f-9fde-3bdf7fe9d335.png">

**Comment by fakhrihawari** [comment]
<img width="699" alt="Screen Shot 2021-09-13 at 10 13 30" src="https://user-images.githubusercontent.com/12655589/133018534-72e42b35-4a01-4e53-bca8-3d7a8bc19a7d.png">

**Comment by fakhrihawari** [comment]
<img width="387" alt="Screen Shot 2021-09-13 at 10 42 15" src="https://user-images.githubusercontent.com/12655589/133020689-d87445f6-5351-4058-b3e9-08a5fa70f829.png">

<img width="426" alt="Screen Shot 2021-09-13 at 10 42 48" src="https://user-images.githubusercontent.com/12655589/133020734-bd9f13c5-b1e3-4978-a8de-bc8053fd3922.png">

<img width="507" alt="Screen Shot 2021-09-13 at 10 43 55" src="https://user-images.githubusercontent.com/12655589/133020827-ec33c21c-7e87-4f94-a3e4-3ef57c4f50c4.png">

**Comment by rafinkanisa** [comment]
this looks good. maybe you could give more padding / margin so it has more space?
maybe you could try also to show the bubble on the right side of the question mark.

**Comment by fakhrihawari** [comment]
<img width="592" alt="Screen Shot 2021-09-14 at 12 37 23" src="https://user-images.githubusercontent.com/12655589/133201028-3bbbbbcf-dee0-4257-a421-28c7262ef309.png">

<img width="629" alt="Screen Shot 2021-09-14 at 12 37 02" src="https://user-images.githubusercontent.com/12655589/133202431-c9d8aec4-0cb2-4cf8-b5aa-977e81a64e88.png">

**Comment by fakhrihawari** [comment]
<img width="5" alt="Screen Shot 2021-09-14 at 12 37 16" src="https://user-images.githubusercontent.com/12655589/133202245-236fb749-cbdb-4c5c-a841-5753b0233372.png">

**Comment by fakhrihawari** [comment]
<img width="592" alt="Screen Shot 2021-09-14 at 12 37 23" src="https://user-images.githubusercontent.com/12655589/133202284-25308abd-6789-47a3-8fa7-c0db7d1f46ac.png">
<img width="5" alt="Screen Shot 2021-09-14 at 12 37 16" src="https://user-images.githubusercontent.com/12655589/133202291-b2e138a9-7c47-46df-b328-603c7240c54d.png">

**Comment by fakhrihawari** [comment]
<img width="5" alt="Screen Shot 2021-09-14 at 12 37 16" src="https://user-images.githubusercontent.com/12655589/133202381-7f8a06d7-d1d1-4c69-a06b-e6f5eced4ceb.png">

**Comment by rafinkanisa** [comment]
This one looks good. please update it on DEV so I could check and after that we proceed to update it on PROD

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/242
