### ISSUE TITLE
Show Activity Response in the Downloaded Data

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#92]
I've just realized that the activity response isn't visible in the downloaded data.
The column which is visible in the downloaded data right now only the project_detail.
For the specific activity, even the partners specifying it, it didn't show in the downloaded data.
I'm not sure if this was on purpose or not.

If somehow the team previously forgot to put this in the downloaded data, please enable this.

Therefore the IMOs could use the data to make visualization more precise.

**Comment by rafinkanisa** [comment]
response_name (COViD-19) is a bit different with the project_details / activity_details (COVID-19 Response)

I think this should be the same for all data in the database.

also, what about the response_id? Shouldn't we include it also in the downloaded data?

**Comment by rafinkanisa** [comment]
no need to update the activities.csv

just used as is

**Comment by fakhrihawari** [comment]
PR
https://github.com/drfaustusfade/ngm-reportEngine/pull/52
