### ISSUE TITLE
Activity Response not ticked using Import in Monthly Progress

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#93]
I've just checked in Monthly Progress, if the user choose to import a file in Monthly Progress, they should still ticked the Activity Response (Winterization/COVID-19) manually. There's no problem with the activity specifying the type of the response in the activity_details though.

This is because the column is not specified and the system currently doesn't have the functionality to automatically ticked the Activity Response when specified in the imported file.

TO DO :
- [x] Make the new import template for Monthly Progress
- [x] Make the system automatically ticked the correspondent Activity Response once a file is being imported

Let me know the challenges.

**Comment by rafinkanisa** [comment]
I've tried in DEV but still not ticked

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/250
