### ISSUE TITLE
Edit the warning text when Mark Activity Complete

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#97]
Because some of the partners are often marking the activity as complete, I think we'll need to update the warning message.

The current warning message :
<img width="931" alt="Screen Shot 2021-09-06 at 19 27 25" src="https://user-images.githubusercontent.com/28089698/132217461-a938e80c-16c7-45e1-b245-776bf608519f.png">

Change to below :
You are going to **Mark this project as Complete**.
It'll **prevent** you / other colleagues to **report the ongoing / coming month**.

Are you sure you want to mark this PROJECT as 'COMPLETE'?

**Comment by fakhrihawari** [comment]
<img width="936" alt="Screen Shot 2021-09-07 at 09 55 48" src="https://user-images.githubusercontent.com/12655589/132277448-4363f780-2e2d-40b4-80e6-c55ba6b16613.png">

**Comment by rafinkanisa** [comment]
How does it look like if you enter the "It'll prevent ....."
then enter again the "Are you sure ...."

**Comment by fakhrihawari** [comment]
<img width="988" alt="Screen Shot 2021-09-07 at 12 47 14" src="https://user-images.githubusercontent.com/12655589/132290831-5f263d87-2164-4997-b8f6-6391efdf5a2e.png">

Like this or below

**Comment by fakhrihawari** [comment]
![Uploading Screen Shot 2021-09-07 at 12.47.57.png…]()

**Comment by fakhrihawari** [comment]
<img width="937" alt="Screen Shot 2021-09-07 at 12 47 57" src="https://user-images.githubusercontent.com/12655589/132290950-7dc390a3-ed96-4bfd-ad0c-eb0d7d4600f7.png">

**Comment by rafinkanisa** [comment]
I think the upper one is better. What do you think?

**Comment by fakhrihawari** [comment]
okay

**Comment by rafinkanisa** [comment]
please give the branch here

**Comment by fakhrihawari** [comment]
Link PR: https://github.com/drfaustusfade/ngm-reportHub/pull/235
