### ISSUE TITLE
Old Beneficiary Type still choosen

### ISSUE THREAD

**Issue by rafinkanisa** [rafinkanisa/ngm-reportDesk#99]
This is a possible bug.

Check below project
https://reporthub.org/desk/#/cluster/projects/report/5dee19f3387fe68671f79b70/60dd21a3603fd1e22450c28d

If you download the monthly progress for July 2021, you could see old beneficiary is still being chosen. Kindly check what's wrong.
<img width="1191" alt="Screen Shot 2021-09-07 at 16 05 28" src="https://user-images.githubusercontent.com/28089698/132317828-92e33e69-c85c-4881-8b81-7ef651f96494.png">

**Comment by fakhrihawari** [comment]
PR 
https://github.com/drfaustusfade/ngm-reportHub/pull/250
